/** biome-ignore-all lint/style/noProcessEnv: This is generated by Prismic */
import {
	type ClientConfig,
	createClient as createPrismicClient,
} from "@prismicio/client";
import { enableAutoPreviews } from "@prismicio/next";
import config from "../slicemachine.config.json" with { type: "json" };

/**
 * The project's Prismic repository name.
 */
export const repositoryName =
	process.env.NEXT_PUBLIC_PRISMIC_ENVIRONMENT || config.repositoryName;

/**
 * A list of Route Resolver objects that define how a document's `url` field is resolved.
 *
 * {@link https://prismic.io/docs/route-resolver#route-resolver}
 */
// TODO: Update the routes array to match your project's route structure.
const routes: ClientConfig["routes"] = [
	// Examples:
	// {
	// 	type: "homepage",
	// 	path: "/",
	// },
	// {
	// 	type: "page",
	// 	path: "/:uid",
	// },
];

/**
 * Creates a Prismic client for the project's repository. The client is used to
 * query content from the Prismic API.
 *
 * @param config - Configuration for the Prismic client.
 */
export const createClient = (c: ClientConfig = {}) => {
	const client = createPrismicClient(repositoryName, {
		fetchOptions:
			process.env.NODE_ENV === "production"
				? { cache: "force-cache", next: { tags: ["prismic"] } }
				: { next: { revalidate: 5 } },
		routes,
		...c,
	});

	enableAutoPreviews({
		client,
	});

	return client;
};
