version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres-test-db
    environment:
      POSTGRES_USER: squared
      POSTGRES_PASSWORD: squared
      POSTGRES_DB: squared-test
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-testing:
    image: postgres:16
    container_name: postgres-testing-db
    environment:
      POSTGRES_USER: squared
      POSTGRES_PASSWORD: squared
      POSTGRES_DB: squared-testing
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql-test/data
      

volumes:
  postgres_data:
