version: 0.2

env:
  secrets-manager:
    DOMAIN: "squared-envs:DOMAIN"
    EMAIL_USERNAME: "squared-envs:EMAIL_USERNAME"
    EMAIL_PASSWORD: "squared-envs:EMAIL_PASSWORD"
    CLIENT_ID: "squared-envs:CLIENT_ID"
    HOOKDECK_AUTH_TOKEN: "squared-envs:HOOKDECK_AUTH_TOKEN"
    JWT_SECRECT: "squared-envs:JWT_SECRECT"
    MONGO_URL: "squared-envs:MONGO_URL"
    NEXTAUTH_SECRET: "squared-envs:NEXTAUTH_SECRET"
    NEXT_PUBLIC_CLIENT_ID: "squared-envs:NEXT_PUBLIC_CLIENT_ID"
    NEXT_PUBLIC_CONFIRM_URL: "squared-envs:NEXT_PUBLIC_CONFIRM_URL"
    NEXT_PUBLIC_GITHUB_CLIENT_SECRET: "squared-envs:NEXT_PUBLIC_GITHUB_CLIENT_SECRET"
    NEXT_PUBLIC_SERVER: "squared-envs:NEXT_PUBLIC_SERVER"
    NEXT_PUBLIC_URL: "squared-envs:NEXT_PUBLIC_URL"
    NODE_ENV: "squared-envs:NODE_ENV"
    PORT: "squared-envs:PORT"
    SEED_PASSWORD: "squared-envs:SEED_PASSWORD"
    GOOGLE_CLIENT_ID: "squared-envs:GOOGLE_CLIENT_ID"
    GOOGLE_CLIENT_SECRET: "squared-envs:GOOGLE_CLIENT_SECRET"
    GITHUB_CLIENT_ID: "squared-envs:GITHUB_CLIENT_ID"
    GITHUB_CLIENT_SECRET: "squared-envs:GITHUB_CLIENT_SECRET"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URI
      - echo Creating .env file...
      - echo "MONGO_URL=$MONGO_URL" >> .env
      - echo "DOMAIN=$DOMAIN" >> .env
      - echo "JWT_SECRECT=$JWT_SECRECT" >> .env
      - echo "EMAIL_USERNAME=$EMAIL_USERNAME" >> .env
      - echo "EMAIL_PASSWORD=$EMAIL_PASSWORD" >> .env
      - echo "PORT=$PORT" >> .env
      - echo "NODE_ENV=$NODE_ENV" >> .env
      - echo "NEXT_PUBLIC_CONFIRM_URL=$NEXT_PUBLIC_CONFIRM_URL" >> .env
      - echo "NEXT_PUBLIC_SERVER=$NEXT_PUBLIC_SERVER" >> .env
      - echo "HOOKDECK_AUTH_TOKEN=$HOOKDECK_AUTH_TOKEN" >> .env
      - echo "CLIENT_ID=$CLIENT_ID" >> .env
      - echo "SEED_PASSWORD=$SEED_PASSWORD" >> .env
      - echo "GITHUB_APP_ID=$GITHUB_APP_ID" >> .env
      - echo "GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID" >> .env
      - echo "GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET" >> .env
      - echo "GITHUB_PRIVATE_KEY=$GITHUB_PRIVATE_KEY" >> .env
      - echo "NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL" >> .env
      - echo "NEXT_PUBLIC_CLIENT_ID=$NEXT_PUBLIC_CLIENT_ID" >> .env
      - echo "NEXT_PUBLIC_GITHUB_CLIENT_SECRET=$NEXT_PUBLIC_GITHUB_CLIENT_SECRET" >> .env
      - echo "NEXT_PUBLIC_GITHUB_CLIENT_ID=$NEXT_PUBLIC_GITHUB_CLIENT_ID" >> .env
      - echo "NEXT_PUBLIC_GITHUB_REDIRECT_URI=$NEXT_PUBLIC_GITHUB_REDIRECT_URI" >> .env
      - echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
      - echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env
      - echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env

      - echo Building Docker images...
      - DOCKER_BUILDKIT=1 docker-compose build --progress=plain

  build:
    commands:
      - echo Tagging Docker images...
      - docker tag squared-www:latest $ECR_REGISTRY_URI/squared-www:latest
      - docker tag squared-web:latest $ECR_REGISTRY_URI/squared-web:latest
      - docker tag squared-api:latest $ECR_REGISTRY_URI/squared-api:latest
      - docker tag squared-nginx:latest $ECR_REGISTRY_URI/squared-nginx:latest

  post_build:
    commands:
      - echo Pushing Docker images to Amazon ECR...
      - docker push $ECR_REGISTRY_URI/squared-www:latest
      - docker push $ECR_REGISTRY_URI/squared-web:latest
      - docker push $ECR_REGISTRY_URI/squared-api:latest
      - docker push $ECR_REGISTRY_URI/squared-nginx:latest

artifacts:
  files:
    - "**/*"

cache:
  paths:
    - "/var/lib/docker"
    - "/root/.cache/buildkit"
