version: "3"

services:
  # www:
  #   container_name: www
  #   build:
  #     context: .
  #     dockerfile: ./apps/www/Dockerfile
  #   image: squared-www:latest
  #   restart: always
  #   ports:
  #     - 4000:4000
  #   networks:
  #     - app_network
  #   env_file:
  #     - .env

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    image: squared-web:latest
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    env_file:
      - .env

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 5173:5173
    networks:
      - app_network
    env_file:
      - .env
    image: squared-api:latest

networks:
  app_network:
    external: true
