[phases.setup]
nixPkgs = ["openssl"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run db:generate", "bun run build --filter=api..."]

[start]
cmd = "cd apps/api && bun src/api/index.ts"
