// Code generated by RPC Client Generator, DO NOT EDIT.
package rpc

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

// GithubService represents the RPC client for the github service
type GithubService struct {
	baseURL string
	client  *http.Client
}

// NewGithubService creates a new instance of GithubService
func NewGithubService(baseURL string) *GithubService {
	return &GithubService{
		baseURL: baseURL,
		client:  &http.Client{Timeout: 60 * time.Second},
	}
}



// GetWorkspaceOrganizationsRequest represents the request for getWorkspaceOrganizations method
type GetWorkspaceOrganizationsRequest struct {
	WorkspaceId string `json:"workspaceId"`
}



// GetWorkspaceOrganizationsResponse represents the response for getWorkspaceOrganizations method
type GetWorkspaceOrganizationsResponse []struct {
	CreatedAt time.Time `json:"createdAt"`
	Name string `json:"name"`
}


// GetWorkspaceOrganizations calls the getWorkspaceOrganizations RPC method
func (s *GithubService) GetWorkspaceOrganizations(ctx context.Context, req GetWorkspaceOrganizationsRequest) (*GetWorkspaceOrganizationsResponse, error) {
	endpoint := fmt.Sprintf("%s/github/getWorkspaceOrganizations", s.baseURL)

	
	wrappedReq := struct {
		JSON GetWorkspaceOrganizationsRequest "json:\"json\""
	}{
		JSON: req,
	}

	reqBody, err := json.Marshal(wrappedReq)
	if err != nil {
		return nil, fmt.Errorf("error marshaling request: %w", err)
	}
	

	httpReq, err := http.NewRequestWithContext(ctx, "POST", endpoint, bytes.NewBuffer(reqBody))
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	requestID := make([]byte, 6)
	if _, err := rand.Read(requestID); err != nil {
		return nil, fmt.Errorf("error generating request ID: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("X-Request-ID", base64.URLEncoding.EncodeToString(requestID))

	resp, err := s.client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("unexpected status code: %d, body: %s", resp.StatusCode, string(body))
	}

	
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("error reading response body: %w", err)
	}

	type GetWorkspaceOrganizationsResponseWrapper struct {
		JSON GetWorkspaceOrganizationsResponse "json:\"json\""
	}

	var responseString string
	if err := json.Unmarshal(body, &responseString); err != nil {
		return nil, fmt.Errorf("error decoding response string: %w", err)
	}

	var wrapper GetWorkspaceOrganizationsResponseWrapper
	if err := json.Unmarshal([]byte(responseString), &wrapper); err != nil {
		return nil, fmt.Errorf("error decoding wrapped response: %w", err)
	}

	return &wrapper.JSON, nil
	
}


// UpsertPullRequestRequest represents the request for upsertPullRequest method
type UpsertPullRequestRequest struct {
	Author string `json:"author"`
	Body string `json:"body"`
	Branch string `json:"branch"`
	Id string `json:"id"`
	Number int `json:"number"`
	Org struct {
	Description *string `json:"description"`
	Id string `json:"id"`
	Name string `json:"name"`
} `json:"org"`
	Repo struct {
	Description *string `json:"description"`
	Id string `json:"id"`
	Name string `json:"name"`
	OrgId string `json:"orgId"`
	Private bool `json:"private"`
	Url string `json:"url"`
} `json:"repo"`
	State string `json:"state"`
	Timestamp string `json:"timestamp"`
	Title string `json:"title"`
	Url string `json:"url"`
}



// UpsertPullRequestResponse represents the response for upsertPullRequest method
type UpsertPullRequestResponse struct {
	Tasks []struct {
	Identifier string `json:"identifier"`
	Title string `json:"title"`
	Url string `json:"url"`
} `json:"tasks"`
}


// UpsertPullRequest calls the upsertPullRequest RPC method
func (s *GithubService) UpsertPullRequest(ctx context.Context, req UpsertPullRequestRequest) (*UpsertPullRequestResponse, error) {
	endpoint := fmt.Sprintf("%s/github/upsertPullRequest", s.baseURL)

	
	wrappedReq := struct {
		JSON UpsertPullRequestRequest "json:\"json\""
	}{
		JSON: req,
	}

	reqBody, err := json.Marshal(wrappedReq)
	if err != nil {
		return nil, fmt.Errorf("error marshaling request: %w", err)
	}
	

	httpReq, err := http.NewRequestWithContext(ctx, "POST", endpoint, bytes.NewBuffer(reqBody))
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	requestID := make([]byte, 6)
	if _, err := rand.Read(requestID); err != nil {
		return nil, fmt.Errorf("error generating request ID: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("X-Request-ID", base64.URLEncoding.EncodeToString(requestID))

	resp, err := s.client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("unexpected status code: %d, body: %s", resp.StatusCode, string(body))
	}

	
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("error reading response body: %w", err)
	}

	type UpsertPullRequestResponseWrapper struct {
		JSON UpsertPullRequestResponse "json:\"json\""
	}

	var responseString string
	if err := json.Unmarshal(body, &responseString); err != nil {
		return nil, fmt.Errorf("error decoding response string: %w", err)
	}

	var wrapper UpsertPullRequestResponseWrapper
	if err := json.Unmarshal([]byte(responseString), &wrapper); err != nil {
		return nil, fmt.Errorf("error decoding wrapped response: %w", err)
	}

	return &wrapper.JSON, nil
	
}


// MergePullRequestRequest represents the request for mergePullRequest method
type MergePullRequestRequest struct {
	PullRequestId string `json:"pullRequestId"`
}



// MergePullRequestResponse represents the response for mergePullRequest method
type MergePullRequestResponse struct{}


// MergePullRequest calls the mergePullRequest RPC method
func (s *GithubService) MergePullRequest(ctx context.Context, req MergePullRequestRequest) (*MergePullRequestResponse, error) {
	endpoint := fmt.Sprintf("%s/github/mergePullRequest", s.baseURL)

	
	wrappedReq := struct {
		JSON MergePullRequestRequest "json:\"json\""
	}{
		JSON: req,
	}

	reqBody, err := json.Marshal(wrappedReq)
	if err != nil {
		return nil, fmt.Errorf("error marshaling request: %w", err)
	}
	

	httpReq, err := http.NewRequestWithContext(ctx, "POST", endpoint, bytes.NewBuffer(reqBody))
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	requestID := make([]byte, 6)
	if _, err := rand.Read(requestID); err != nil {
		return nil, fmt.Errorf("error generating request ID: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("X-Request-ID", base64.URLEncoding.EncodeToString(requestID))

	resp, err := s.client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("unexpected status code: %d, body: %s", resp.StatusCode, string(body))
	}

	
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("error reading response body: %w", err)
	}

	type MergePullRequestResponseWrapper struct {
		JSON MergePullRequestResponse "json:\"json\""
	}

	var responseString string
	if err := json.Unmarshal(body, &responseString); err != nil {
		return nil, fmt.Errorf("error decoding response string: %w", err)
	}

	var wrapper MergePullRequestResponseWrapper
	if err := json.Unmarshal([]byte(responseString), &wrapper); err != nil {
		return nil, fmt.Errorf("error decoding wrapped response: %w", err)
	}

	return &wrapper.JSON, nil
	
}


// ClosePullRequestRequest represents the request for closePullRequest method
type ClosePullRequestRequest struct {
	PullRequestId string `json:"pullRequestId"`
}



// ClosePullRequestResponse represents the response for closePullRequest method
type ClosePullRequestResponse struct{}


// ClosePullRequest calls the closePullRequest RPC method
func (s *GithubService) ClosePullRequest(ctx context.Context, req ClosePullRequestRequest) (*ClosePullRequestResponse, error) {
	endpoint := fmt.Sprintf("%s/github/closePullRequest", s.baseURL)

	
	wrappedReq := struct {
		JSON ClosePullRequestRequest "json:\"json\""
	}{
		JSON: req,
	}

	reqBody, err := json.Marshal(wrappedReq)
	if err != nil {
		return nil, fmt.Errorf("error marshaling request: %w", err)
	}
	

	httpReq, err := http.NewRequestWithContext(ctx, "POST", endpoint, bytes.NewBuffer(reqBody))
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	requestID := make([]byte, 6)
	if _, err := rand.Read(requestID); err != nil {
		return nil, fmt.Errorf("error generating request ID: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("X-Request-ID", base64.URLEncoding.EncodeToString(requestID))

	resp, err := s.client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("unexpected status code: %d, body: %s", resp.StatusCode, string(body))
	}

	
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("error reading response body: %w", err)
	}

	type ClosePullRequestResponseWrapper struct {
		JSON ClosePullRequestResponse "json:\"json\""
	}

	var responseString string
	if err := json.Unmarshal(body, &responseString); err != nil {
		return nil, fmt.Errorf("error decoding response string: %w", err)
	}

	var wrapper ClosePullRequestResponseWrapper
	if err := json.Unmarshal([]byte(responseString), &wrapper); err != nil {
		return nil, fmt.Errorf("error decoding wrapped response: %w", err)
	}

	return &wrapper.JSON, nil
	
}


// PushCommitRequest represents the request for pushCommit method
type PushCommitRequest struct {
	Author string `json:"author"`
	Branch string `json:"branch"`
	Id string `json:"id"`
	Message string `json:"message"`
	RepoId string `json:"repoId"`
	Timestamp string `json:"timestamp"`
	Url string `json:"url"`
}



// PushCommitResponse represents the response for pushCommit method
type PushCommitResponse struct{}


// PushCommit calls the pushCommit RPC method
func (s *GithubService) PushCommit(ctx context.Context, req PushCommitRequest) (*PushCommitResponse, error) {
	endpoint := fmt.Sprintf("%s/github/pushCommit", s.baseURL)

	
	wrappedReq := struct {
		JSON PushCommitRequest "json:\"json\""
	}{
		JSON: req,
	}

	reqBody, err := json.Marshal(wrappedReq)
	if err != nil {
		return nil, fmt.Errorf("error marshaling request: %w", err)
	}
	

	httpReq, err := http.NewRequestWithContext(ctx, "POST", endpoint, bytes.NewBuffer(reqBody))
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	requestID := make([]byte, 6)
	if _, err := rand.Read(requestID); err != nil {
		return nil, fmt.Errorf("error generating request ID: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("X-Request-ID", base64.URLEncoding.EncodeToString(requestID))

	resp, err := s.client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("unexpected status code: %d, body: %s", resp.StatusCode, string(body))
	}

	
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("error reading response body: %w", err)
	}

	type PushCommitResponseWrapper struct {
		JSON PushCommitResponse "json:\"json\""
	}

	var responseString string
	if err := json.Unmarshal(body, &responseString); err != nil {
		return nil, fmt.Errorf("error decoding response string: %w", err)
	}

	var wrapper PushCommitResponseWrapper
	if err := json.Unmarshal([]byte(responseString), &wrapper); err != nil {
		return nil, fmt.Errorf("error decoding wrapped response: %w", err)
	}

	return &wrapper.JSON, nil
	
}


// UploadOrgRequest represents the request for uploadOrg method
type UploadOrgRequest struct {
	Description string `json:"description"`
	Id string `json:"id"`
	Name string `json:"name"`
	WorkspaceId string `json:"workspaceId"`
}



// UploadOrgResponse represents the response for uploadOrg method
type UploadOrgResponse struct {
	Slug string `json:"slug"`
}


// UploadOrg calls the uploadOrg RPC method
func (s *GithubService) UploadOrg(ctx context.Context, req UploadOrgRequest) (*UploadOrgResponse, error) {
	endpoint := fmt.Sprintf("%s/github/uploadOrg", s.baseURL)

	
	wrappedReq := struct {
		JSON UploadOrgRequest "json:\"json\""
	}{
		JSON: req,
	}

	reqBody, err := json.Marshal(wrappedReq)
	if err != nil {
		return nil, fmt.Errorf("error marshaling request: %w", err)
	}
	

	httpReq, err := http.NewRequestWithContext(ctx, "POST", endpoint, bytes.NewBuffer(reqBody))
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	requestID := make([]byte, 6)
	if _, err := rand.Read(requestID); err != nil {
		return nil, fmt.Errorf("error generating request ID: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("X-Request-ID", base64.URLEncoding.EncodeToString(requestID))

	resp, err := s.client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("unexpected status code: %d, body: %s", resp.StatusCode, string(body))
	}

	
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("error reading response body: %w", err)
	}

	type UploadOrgResponseWrapper struct {
		JSON UploadOrgResponse "json:\"json\""
	}

	var responseString string
	if err := json.Unmarshal(body, &responseString); err != nil {
		return nil, fmt.Errorf("error decoding response string: %w", err)
	}

	var wrapper UploadOrgResponseWrapper
	if err := json.Unmarshal([]byte(responseString), &wrapper); err != nil {
		return nil, fmt.Errorf("error decoding wrapped response: %w", err)
	}

	return &wrapper.JSON, nil
	
}

