// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Docs Landing Page → Featured Sections*
 */
export interface DocsDocumentDataFeaturedSectionsItem {
  /**
   * Section field in *Docs Landing Page → Featured Sections*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: docs.featured_sections[].section
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  section: prismic.ContentRelationshipField<"documentation">;

  /**
   * Description field in *Docs Landing Page → Featured Sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Brief description of this section
   * - **API ID Path**: docs.featured_sections[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

type DocsDocumentDataSlicesSlice = never;

/**
 * Content for Docs Landing Page documents
 */
interface DocsDocumentData {
  /**
   * Title field in *Docs Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Documentation
   * - **API ID Path**: docs.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Introduction field in *Docs Landing Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Welcome to our documentation...
   * - **API ID Path**: docs.introduction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  introduction: prismic.RichTextField;

  /**
   * Featured Sections field in *Docs Landing Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: docs.featured_sections[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featured_sections: prismic.GroupField<
    Simplify<DocsDocumentDataFeaturedSectionsItem>
  >;

  /**
   * Slice Zone field in *Docs Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: docs.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DocsDocumentDataSlicesSlice> /**
   * Meta Title field in *Docs Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: docs.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Docs Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: docs.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Docs Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: docs.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Docs Landing Page document from Prismic
 *
 * - **API ID**: `docs`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DocsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<DocsDocumentData>, "docs", Lang>;

type DocumentationDocumentDataSlicesSlice = never;

/**
 * Content for Documentation documents
 */
interface DocumentationDocumentData {
  /**
   * Title field in *Documentation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: documentation.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Parent field in *Documentation*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: documentation.parent_page
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent_page: prismic.ContentRelationshipField<"documentation">;

  /**
   * Order field in *Documentation*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Order within its level (e.g., 1, 2, 3)
   * - **API ID Path**: documentation.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;

  /**
   * Slice Zone field in *Documentation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: documentation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DocumentationDocumentDataSlicesSlice> /**
   * Meta Title field in *Documentation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: documentation.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Documentation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: documentation.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Documentation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: documentation.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Documentation document from Prismic
 *
 * - **API ID**: `documentation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DocumentationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DocumentationDocumentData>,
    "documentation",
    Lang
  >;

export type AllDocumentTypes = DocsDocument | DocumentationDocument;

/**
 * Primary content in *Header → heading1 → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * title field in *Header → heading1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *Header → heading1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * heading1 variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Header → heading2 → Primary*
 */
export interface HeaderSliceVeryLargePrimary {
  /**
   * title field in *Header → heading2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.veryLarge.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *Header → heading2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.veryLarge.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * heading2 variation for Header Slice
 *
 * - **API ID**: `veryLarge`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceVeryLarge = prismic.SharedSliceVariation<
  "veryLarge",
  Simplify<HeaderSliceVeryLargePrimary>,
  never
>;

/**
 * Primary content in *Header → heading3 → Primary*
 */
export interface HeaderSliceLargePrimary {
  /**
   * title field in *Header → heading3 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.large.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *Header → heading3 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.large.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * heading3 variation for Header Slice
 *
 * - **API ID**: `large`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceLarge = prismic.SharedSliceVariation<
  "large",
  Simplify<HeaderSliceLargePrimary>,
  never
>;

/**
 * Primary content in *Header → heading4 → Primary*
 */
export interface HeaderSliceMediumPrimary {
  /**
   * title field in *Header → heading4 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.medium.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *Header → heading4 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.medium.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * heading4 variation for Header Slice
 *
 * - **API ID**: `medium`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceMedium = prismic.SharedSliceVariation<
  "medium",
  Simplify<HeaderSliceMediumPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation =
  | HeaderSliceDefault
  | HeaderSliceVeryLarge
  | HeaderSliceLarge
  | HeaderSliceMedium;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DocsDocument,
      DocsDocumentData,
      DocsDocumentDataFeaturedSectionsItem,
      DocsDocumentDataSlicesSlice,
      DocumentationDocument,
      DocumentationDocumentData,
      DocumentationDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeaderSlice,
      HeaderSliceDefaultPrimary,
      HeaderSliceVeryLargePrimary,
      HeaderSliceLargePrimary,
      HeaderSliceMediumPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HeaderSliceVeryLarge,
      HeaderSliceLarge,
      HeaderSliceMedium,
    };
  }
}
