// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AccordionDocumentDataSlicesSlice = never;

/**
 * Content for accordion documents
 */
interface AccordionDocumentData {
  /**
   * title field in *accordion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * order field in *accordion*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;

  /**
   * parent field in *accordion*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.LinkField;

  /**
   * `slices` field in *accordion*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AccordionDocumentDataSlicesSlice>;
}

/**
 * accordion document from Prismic
 *
 * - **API ID**: `accordion`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AccordionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AccordionDocumentData>,
    "accordion",
    Lang
  >;

/**
 * Item in *child accordion → accordion content*
 */
export interface ChildAccordionDocumentDataAccordionContentItem {
  /**
   * item slug url field in *child accordion → accordion content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: child_accordion.accordion_content[].item_slug_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_slug_url: prismic.KeyTextField;

  /**
   * item label field in *child accordion → accordion content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: child_accordion.accordion_content[].item_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_label: prismic.KeyTextField;
}

/**
 * Content for child accordion documents
 */
interface ChildAccordionDocumentData {
  /**
   * accordion trigger field in *child accordion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: child_accordion.accordion_trigger
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accordion_trigger: prismic.KeyTextField;

  /**
   * accordion content field in *child accordion*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: child_accordion.accordion_content[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  accordion_content: prismic.GroupField<
    Simplify<ChildAccordionDocumentDataAccordionContentItem>
  >;
}

/**
 * child accordion document from Prismic
 *
 * - **API ID**: `child_accordion`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ChildAccordionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ChildAccordionDocumentData>,
    "child_accordion",
    Lang
  >;

type DocDocumentDataSlicesSlice = BulletPointsSlice | HeaderSlice;

/**
 * Content for doc documents
 */
interface DocDocumentData {
  /**
   * Slice Zone field in *doc*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: doc.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DocDocumentDataSlicesSlice> /**
   * Meta Title field in *doc*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: doc.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *doc*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: doc.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *doc*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: doc.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * doc document from Prismic
 *
 * - **API ID**: `doc`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DocDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<DocDocumentData>, "doc", Lang>;

type DocSidebarDocumentDataSlicesSlice = LinkSlice;

/**
 * Content for doc sidebar documents
 */
interface DocSidebarDocumentData {
  /**
   * Slice Zone field in *doc sidebar*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: doc_sidebar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DocSidebarDocumentDataSlicesSlice> /**
   * Meta Title field in *doc sidebar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: doc_sidebar.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *doc sidebar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: doc_sidebar.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *doc sidebar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: doc_sidebar.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * doc sidebar document from Prismic
 *
 * - **API ID**: `doc_sidebar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DocSidebarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DocSidebarDocumentData>,
    "doc_sidebar",
    Lang
  >;

export type AllDocumentTypes =
  | AccordionDocument
  | ChildAccordionDocument
  | DocDocument
  | DocSidebarDocument;

/**
 * Default variation for Accordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Accordion*
 */
type AccordionSliceVariation = AccordionSliceDefault;

/**
 * Accordion Shared Slice
 *
 * - **API ID**: `accordion`
 * - **Description**: Accordion
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSlice = prismic.SharedSlice<
  "accordion",
  AccordionSliceVariation
>;

/**
 * Primary content in *Lists → bullet → Primary*
 */
export interface BulletPointsSliceDefaultPrimary {
  /**
   * bullet list field in *Lists → bullet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bullet_points.default.primary.bullet_list
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bullet_list: prismic.RichTextField;
}

/**
 * bullet variation for Lists Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BulletPointsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BulletPointsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Lists*
 */
type BulletPointsSliceVariation = BulletPointsSliceDefault;

/**
 * Lists Shared Slice
 *
 * - **API ID**: `bullet_points`
 * - **Description**: BulletPoints
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BulletPointsSlice = prismic.SharedSlice<
  "bullet_points",
  BulletPointsSliceVariation
>;

/**
 * Primary content in *Header → heading1 → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * title field in *Header → heading1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *Header → heading1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * heading1 variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Header → heading2 → Primary*
 */
export interface HeaderSliceVeryLargePrimary {
  /**
   * title field in *Header → heading2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.veryLarge.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *Header → heading2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.veryLarge.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * heading2 variation for Header Slice
 *
 * - **API ID**: `veryLarge`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceVeryLarge = prismic.SharedSliceVariation<
  "veryLarge",
  Simplify<HeaderSliceVeryLargePrimary>,
  never
>;

/**
 * Primary content in *Header → heading3 → Primary*
 */
export interface HeaderSliceLargePrimary {
  /**
   * title field in *Header → heading3 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.large.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *Header → heading3 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.large.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * heading3 variation for Header Slice
 *
 * - **API ID**: `large`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceLarge = prismic.SharedSliceVariation<
  "large",
  Simplify<HeaderSliceLargePrimary>,
  never
>;

/**
 * Primary content in *Header → heading4 → Primary*
 */
export interface HeaderSliceMediumPrimary {
  /**
   * title field in *Header → heading4 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.medium.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *Header → heading4 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.medium.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * heading4 variation for Header Slice
 *
 * - **API ID**: `medium`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceMedium = prismic.SharedSliceVariation<
  "medium",
  Simplify<HeaderSliceMediumPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation =
  | HeaderSliceDefault
  | HeaderSliceVeryLarge
  | HeaderSliceLarge
  | HeaderSliceMedium;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero.default.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * callToActionLink field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Image Right → Primary*
 */
export interface HeroSliceImageRightPrimary {
  /**
   * eyebrowHeadline field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero.imageRight.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.imageRight.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.imageRight.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.imageRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * callToActionLink field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.imageRight.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;
}

/**
 * Image Right variation for Hero Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<HeroSliceImageRightPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceImageRight;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Link → accordion → Primary → accordion content*
 */
export interface LinkSliceAccordionPrimaryAccordionContentItem {
  /**
   * item slug url field in *Link → accordion → Primary → accordion content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link.accordion.primary.accordion_content[].item_slug_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_slug_url: prismic.KeyTextField;

  /**
   * item label field in *Link → accordion → Primary → accordion content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link.accordion.primary.accordion_content[].item_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_label: prismic.KeyTextField;
}

/**
 * Primary content in *Link → Default → Primary*
 */
export interface LinkSliceDefaultPrimary {
  /**
   * label field in *Link → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  label: prismic.LinkField;

  /**
   * slug field in *Link → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link.default.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;
}

/**
 * Default variation for Link Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Link → accordion → Primary*
 */
export interface LinkSliceAccordionPrimary {
  /**
   * accordion trigger field in *Link → accordion → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link.accordion.primary.accordion_trigger
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accordion_trigger: prismic.KeyTextField;

  /**
   * accordion content field in *Link → accordion → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: link.accordion.primary.accordion_content[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  accordion_content: prismic.GroupField<
    Simplify<LinkSliceAccordionPrimaryAccordionContentItem>
  >;

  /**
   * nested accordion field in *Link → accordion → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: link.accordion.primary.nested_accordion
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nested_accordion: prismic.ContentRelationshipField<"child_accordion">;
}

/**
 * accordion variation for Link Slice
 *
 * - **API ID**: `accordion`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSliceAccordion = prismic.SharedSliceVariation<
  "accordion",
  Simplify<LinkSliceAccordionPrimary>,
  never
>;

/**
 * Slice variation for *Link*
 */
type LinkSliceVariation = LinkSliceDefault | LinkSliceAccordion;

/**
 * Link Shared Slice
 *
 * - **API ID**: `link`
 * - **Description**: Link
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSlice = prismic.SharedSlice<"link", LinkSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AccordionDocument,
      AccordionDocumentData,
      AccordionDocumentDataSlicesSlice,
      ChildAccordionDocument,
      ChildAccordionDocumentData,
      ChildAccordionDocumentDataAccordionContentItem,
      DocDocument,
      DocDocumentData,
      DocDocumentDataSlicesSlice,
      DocSidebarDocument,
      DocSidebarDocumentData,
      DocSidebarDocumentDataSlicesSlice,
      AllDocumentTypes,
      AccordionSlice,
      AccordionSliceVariation,
      AccordionSliceDefault,
      BulletPointsSlice,
      BulletPointsSliceDefaultPrimary,
      BulletPointsSliceVariation,
      BulletPointsSliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimary,
      HeaderSliceVeryLargePrimary,
      HeaderSliceLargePrimary,
      HeaderSliceMediumPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HeaderSliceVeryLarge,
      HeaderSliceLarge,
      HeaderSliceMedium,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceImageRightPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceImageRight,
      LinkSlice,
      LinkSliceDefaultPrimary,
      LinkSliceAccordionPrimaryAccordionContentItem,
      LinkSliceAccordionPrimary,
      LinkSliceVariation,
      LinkSliceDefault,
      LinkSliceAccordion,
    };
  }
}
