// Code generated by generate-index.ts, DO NOT EDIT.
/* eslint-disable */
import { Router } from "express";
import { Route, toQueryHandler, toMutationHandler } from "./route";
import { PrismaClient } from "@repo/db/src";

export const prisma = new PrismaClient();


import * as $61fb65 from "./team/[teamId]/task";
import * as $0a9f89 from "./team/[teamId]";
import * as $abb393 from "./task/[taskId]";

export type AllRouteDeps =
  & Parameters<typeof $61fb65.createRoute>[0]
  & Parameters<typeof $0a9f89.createRoute>[0]
  & Parameters<typeof $abb393.createRoute>[0]

export function createApiRouter(router: Router, deps: AllRouteDeps) {

  {
    type Params = { teamId: string };
    const r: Route<Params> = $61fb65.createRoute(deps);

    router.get("/api/team/:teamId/task", toQueryHandler(r.GET));
    router.post("/api/team/:teamId/task", toMutationHandler(r.POST));
    router.put("/api/team/:teamId/task", toMutationHandler(r.PUT));
    router.delete("/api/team/:teamId/task", toQueryHandler(r.DELETE));
  }

  {
    type Params = { teamId: string };
    const r: Route<Params> = $0a9f89.createRoute(deps);

    router.get("/api/team/:teamId", toQueryHandler(r.GET));
    router.post("/api/team/:teamId", toMutationHandler(r.POST));
    router.put("/api/team/:teamId", toMutationHandler(r.PUT));
    router.delete("/api/team/:teamId", toQueryHandler(r.DELETE));
  }

  {
    type Params = { taskId: string };
    const r: Route<Params> = $abb393.createRoute(deps);

    router.get("/api/task/:taskId", toQueryHandler(r.GET));
    router.post("/api/task/:taskId", toMutationHandler(r.POST));
    router.put("/api/task/:taskId", toMutationHandler(r.PUT));
    router.delete("/api/task/:taskId", toQueryHandler(r.DELETE));
  }
}
