// Code generated by generate-index.ts, DO NOT EDIT.
/* eslint-disable */
import { Router } from "express";
import { Route, toQueryHandler, toMutationHandler } from "./route";
import { PrismaClient } from "@repo/db/src";

export const prisma = new PrismaClient();


import * as $164d45 from "./workspace/[workspaceId]/[teamId]/task";
import * as $7fdd7f from "./workspace/[workspaceId]/[teamId]/task/[taskId]";

export type AllRouteDeps =
  & Parameters<typeof $164d45.createRoute>[0]
  & Parameters<typeof $7fdd7f.createRoute>[0]

export function createApiRouter(router: Router, deps: AllRouteDeps) {

  {
    type Params = { workspaceId: string; teamId: string };
    const r: Route<Params> = $164d45.createRoute(deps);

    router.get("/api/workspace/:workspaceId/:teamId/task", toQueryHandler(r.GET));
    router.post("/api/workspace/:workspaceId/:teamId/task", toMutationHandler(r.POST));
    router.put("/api/workspace/:workspaceId/:teamId/task", toMutationHandler(r.PUT));
    router.delete("/api/workspace/:workspaceId/:teamId/task", toQueryHandler(r.DELETE));
  }

  {
    type Params = { workspaceId: string; teamId: string; taskId: string };
    const r: Route<Params> = $7fdd7f.createRoute(deps);

    router.get("/api/workspace/:workspaceId/:teamId/task/:taskId", toQueryHandler(r.GET));
    router.post("/api/workspace/:workspaceId/:teamId/task/:taskId", toMutationHandler(r.POST));
    router.put("/api/workspace/:workspaceId/:teamId/task/:taskId", toMutationHandler(r.PUT));
    router.delete("/api/workspace/:workspaceId/:teamId/task/:taskId", toQueryHandler(r.DELETE));
  }
}
