// Code generated by generate-index.ts, DO NOT EDIT.
// @ts-nocheck

import type { Router } from "express";
import * as route0 from "./";
import * as route1 from "./auth";
import * as route2 from "./auth/[token]";
import * as route3 from "./auth/logout";
import * as route4 from "./auth/reset-password";
import * as route5 from "./auth/reset-password/[token]";
import * as route6 from "./comment/[commentId]";
import * as route7 from "./filter/[filterId]";
import * as route8 from "./integration/github/oauth";
import * as route9 from "./integration/github/webhook";
import { toMutationHandler, toQueryHandler } from "./route";
import type { Route } from "./route";
import * as route10 from "./team/[teamId]";
import * as route11 from "./team/[teamId]/sprints";
import * as route12 from "./user/[userId]";
import * as route13 from "./user/[userId]/avatar";
import * as route14 from "./user/[userId]/notification";
import * as route15 from "./user/[userId]/repositories";
import * as route16 from "./user/[userId]/team";
import * as route17 from "./user/[userId]/workspace";
import * as route18 from "./workspace/[workspaceId]";
import * as route19 from "./workspace/[workspaceId]/filter";
import * as route20 from "./workspace/[workspaceId]/invite";
import * as route21 from "./workspace/[workspaceId]/label";
import * as route22 from "./workspace/[workspaceId]/team";
import * as route23 from "./workspace/[workspaceId]/user";
import * as route24 from "./workspace/join";

export type AllRouteDeps = Parameters<typeof route0.createRoute>[0] &
	Parameters<typeof route1.createRoute>[0] &
	Parameters<typeof route2.createRoute>[0] &
	Parameters<typeof route3.createRoute>[0] &
	Parameters<typeof route4.createRoute>[0] &
	Parameters<typeof route5.createRoute>[0] &
	Parameters<typeof route6.createRoute>[0] &
	Parameters<typeof route7.createRoute>[0] &
	Parameters<typeof route8.createRoute>[0] &
	Parameters<typeof route9.createRoute>[0] &
	Parameters<typeof route10.createRoute>[0] &
	Parameters<typeof route11.createRoute>[0] &
	Parameters<typeof route12.createRoute>[0] &
	Parameters<typeof route13.createRoute>[0] &
	Parameters<typeof route14.createRoute>[0] &
	Parameters<typeof route15.createRoute>[0] &
	Parameters<typeof route16.createRoute>[0] &
	Parameters<typeof route17.createRoute>[0] &
	Parameters<typeof route18.createRoute>[0] &
	Parameters<typeof route19.createRoute>[0] &
	Parameters<typeof route20.createRoute>[0] &
	Parameters<typeof route21.createRoute>[0] &
	Parameters<typeof route22.createRoute>[0] &
	Parameters<typeof route23.createRoute>[0] &
	Parameters<typeof route24.createRoute>[0];

export function createApiRouter(router: Router, deps: AllRouteDeps) {
	{
		type Params = Parameters<typeof route0.createRoute>[0];
		const r: Route<Params> = route0.createRoute(deps);
		router.get("/", toQueryHandler(r.GET));
		router.post("/", toMutationHandler(r.POST));
		router.put("/", toMutationHandler(r.PUT));
		router.delete("/", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route1.createRoute>[0];
		const r: Route<Params> = route1.createRoute(deps);
		router.get("/auth", toQueryHandler(r.GET));
		router.post("/auth", toMutationHandler(r.POST));
		router.put("/auth", toMutationHandler(r.PUT));
		router.delete("/auth", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route2.createRoute>[0];
		const r: Route<Params> = route2.createRoute(deps);
		router.get("/auth/:token", toQueryHandler(r.GET));
		router.post("/auth/:token", toMutationHandler(r.POST));
		router.put("/auth/:token", toMutationHandler(r.PUT));
		router.delete("/auth/:token", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route3.createRoute>[0];
		const r: Route<Params> = route3.createRoute(deps);
		router.get("/auth/logout", toQueryHandler(r.GET));
		router.post("/auth/logout", toMutationHandler(r.POST));
		router.put("/auth/logout", toMutationHandler(r.PUT));
		router.delete("/auth/logout", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route4.createRoute>[0];
		const r: Route<Params> = route4.createRoute(deps);
		router.get("/auth/reset-password", toQueryHandler(r.GET));
		router.post("/auth/reset-password", toMutationHandler(r.POST));
		router.put("/auth/reset-password", toMutationHandler(r.PUT));
		router.delete("/auth/reset-password", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route5.createRoute>[0];
		const r: Route<Params> = route5.createRoute(deps);
		router.get("/auth/reset-password/:token", toQueryHandler(r.GET));
		router.post("/auth/reset-password/:token", toMutationHandler(r.POST));
		router.put("/auth/reset-password/:token", toMutationHandler(r.PUT));
		router.delete("/auth/reset-password/:token", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route6.createRoute>[0];
		const r: Route<Params> = route6.createRoute(deps);
		router.get("/comment/:commentId", toQueryHandler(r.GET));
		router.post("/comment/:commentId", toMutationHandler(r.POST));
		router.put("/comment/:commentId", toMutationHandler(r.PUT));
		router.delete("/comment/:commentId", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route7.createRoute>[0];
		const r: Route<Params> = route7.createRoute(deps);
		router.get("/filter/:filterId", toQueryHandler(r.GET));
		router.post("/filter/:filterId", toMutationHandler(r.POST));
		router.put("/filter/:filterId", toMutationHandler(r.PUT));
		router.delete("/filter/:filterId", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route8.createRoute>[0];
		const r: Route<Params> = route8.createRoute(deps);
		router.get("/integration/github/oauth", toQueryHandler(r.GET));
		router.post("/integration/github/oauth", toMutationHandler(r.POST));
		router.put("/integration/github/oauth", toMutationHandler(r.PUT));
		router.delete("/integration/github/oauth", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route9.createRoute>[0];
		const r: Route<Params> = route9.createRoute(deps);
		router.get("/integration/github/webhook", toQueryHandler(r.GET));
		router.post("/integration/github/webhook", toMutationHandler(r.POST));
		router.put("/integration/github/webhook", toMutationHandler(r.PUT));
		router.delete("/integration/github/webhook", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route10.createRoute>[0];
		const r: Route<Params> = route10.createRoute(deps);
		router.get("/team/:teamId", toQueryHandler(r.GET));
		router.post("/team/:teamId", toMutationHandler(r.POST));
		router.put("/team/:teamId", toMutationHandler(r.PUT));
		router.delete("/team/:teamId", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route11.createRoute>[0];
		const r: Route<Params> = route11.createRoute(deps);
		router.get("/team/:teamId/sprints", toQueryHandler(r.GET));
		router.post("/team/:teamId/sprints", toMutationHandler(r.POST));
		router.put("/team/:teamId/sprints", toMutationHandler(r.PUT));
		router.delete("/team/:teamId/sprints", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route12.createRoute>[0];
		const r: Route<Params> = route12.createRoute(deps);
		router.get("/user/:userId", toQueryHandler(r.GET));
		router.post("/user/:userId", toMutationHandler(r.POST));
		router.put("/user/:userId", toMutationHandler(r.PUT));
		router.delete("/user/:userId", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route13.createRoute>[0];
		const r: Route<Params> = route13.createRoute(deps);
		router.get("/user/:userId/avatar", toQueryHandler(r.GET));
		router.post("/user/:userId/avatar", toMutationHandler(r.POST));
		router.put("/user/:userId/avatar", toMutationHandler(r.PUT));
		router.delete("/user/:userId/avatar", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route14.createRoute>[0];
		const r: Route<Params> = route14.createRoute(deps);
		router.get("/user/:userId/notification", toQueryHandler(r.GET));
		router.post("/user/:userId/notification", toMutationHandler(r.POST));
		router.put("/user/:userId/notification", toMutationHandler(r.PUT));
		router.delete("/user/:userId/notification", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route15.createRoute>[0];
		const r: Route<Params> = route15.createRoute(deps);
		router.get("/user/:userId/repositories", toQueryHandler(r.GET));
		router.post("/user/:userId/repositories", toMutationHandler(r.POST));
		router.put("/user/:userId/repositories", toMutationHandler(r.PUT));
		router.delete("/user/:userId/repositories", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route16.createRoute>[0];
		const r: Route<Params> = route16.createRoute(deps);
		router.get("/user/:userId/team", toQueryHandler(r.GET));
		router.post("/user/:userId/team", toMutationHandler(r.POST));
		router.put("/user/:userId/team", toMutationHandler(r.PUT));
		router.delete("/user/:userId/team", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route17.createRoute>[0];
		const r: Route<Params> = route17.createRoute(deps);
		router.get("/user/:userId/workspace", toQueryHandler(r.GET));
		router.post("/user/:userId/workspace", toMutationHandler(r.POST));
		router.put("/user/:userId/workspace", toMutationHandler(r.PUT));
		router.delete("/user/:userId/workspace", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route18.createRoute>[0];
		const r: Route<Params> = route18.createRoute(deps);
		router.get("/workspace/:workspaceId", toQueryHandler(r.GET));
		router.post("/workspace/:workspaceId", toMutationHandler(r.POST));
		router.put("/workspace/:workspaceId", toMutationHandler(r.PUT));
		router.delete("/workspace/:workspaceId", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route19.createRoute>[0];
		const r: Route<Params> = route19.createRoute(deps);
		router.get("/workspace/:workspaceId/filter", toQueryHandler(r.GET));
		router.post("/workspace/:workspaceId/filter", toMutationHandler(r.POST));
		router.put("/workspace/:workspaceId/filter", toMutationHandler(r.PUT));
		router.delete("/workspace/:workspaceId/filter", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route20.createRoute>[0];
		const r: Route<Params> = route20.createRoute(deps);
		router.get("/workspace/:workspaceId/invite", toQueryHandler(r.GET));
		router.post("/workspace/:workspaceId/invite", toMutationHandler(r.POST));
		router.put("/workspace/:workspaceId/invite", toMutationHandler(r.PUT));
		router.delete("/workspace/:workspaceId/invite", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route21.createRoute>[0];
		const r: Route<Params> = route21.createRoute(deps);
		router.get("/workspace/:workspaceId/label", toQueryHandler(r.GET));
		router.post("/workspace/:workspaceId/label", toMutationHandler(r.POST));
		router.put("/workspace/:workspaceId/label", toMutationHandler(r.PUT));
		router.delete("/workspace/:workspaceId/label", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route22.createRoute>[0];
		const r: Route<Params> = route22.createRoute(deps);
		router.get("/workspace/:workspaceId/team", toQueryHandler(r.GET));
		router.post("/workspace/:workspaceId/team", toMutationHandler(r.POST));
		router.put("/workspace/:workspaceId/team", toMutationHandler(r.PUT));
		router.delete("/workspace/:workspaceId/team", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route23.createRoute>[0];
		const r: Route<Params> = route23.createRoute(deps);
		router.get("/workspace/:workspaceId/user", toQueryHandler(r.GET));
		router.post("/workspace/:workspaceId/user", toMutationHandler(r.POST));
		router.put("/workspace/:workspaceId/user", toMutationHandler(r.PUT));
		router.delete("/workspace/:workspaceId/user", toQueryHandler(r.DELETE));
	}
	{
		type Params = Parameters<typeof route24.createRoute>[0];
		const r: Route<Params> = route24.createRoute(deps);
		router.get("/workspace/join", toQueryHandler(r.GET));
		router.post("/workspace/join", toMutationHandler(r.POST));
		router.put("/workspace/join", toMutationHandler(r.PUT));
		router.delete("/workspace/join", toQueryHandler(r.DELETE));
	}
}
