import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import "dotenv/config";
import createCustomLogger from "@squared/logger";

// Define the output path
const outputPath = path.join(__dirname, "index.ts");
const vercelRegex = /^https:\/\/web-(\w+)-squaredmade\.vercel\.app$/;

// Ensure the file is empty before writing to it
fs.writeFileSync(outputPath, "");

// Generate the index and write to file
export function generateIndex() {
	const writeLn = (str: string) => fs.appendFileSync(outputPath, `${str}\n`);

	writeLn(`// Code generated by generate-index.ts, DO NOT EDIT.
// @ts-nocheck

import express from "express";
import cors from "cors";
import http from "node:http";
import { Server } from "socket.io";
import type { Router } from "express";
import { toQueryHandler, toMutationHandler } from "./route";
import type { Route } from "./route";
import { PrismaClient } from "@squared/db";
import createCustomLogger from "@squared/logger";
import { createErrorHandler, createRequestHandler } from "@squared/rpc";
import { rpcHandlers } from "@/services";
import { setupSwagger } from "../../swagger";
import "dotenv/config";

export const prisma = new PrismaClient({
	datasources: {
		db: {
			url: process.env.POSTGRES_PRISMA_URL,
		},
	},
});

const logger = createCustomLogger("api");

`);

	const files = getRoutes(__dirname)
		.map((p) => p.replace(__dirname, "."))
		.filter((p) => p !== ".");

	const filenameHashes: string[] = [];

	for (let i = 0; i < files.length; i++) {
		const hash = createHash("sha1").update(files[i]).digest().subarray(-3);
		while (filenameHashes.includes(hash.toString("hex"))) {
			hash[0]++;
		}
		filenameHashes.push(hash.toString("hex"));

		writeLn(`import * as $${filenameHashes[i]} from "${files[i]}";`);
	}

	writeLn("\nexport type AllRouteDeps =");
	for (let i = 0; i < files.length; i++) {
		writeLn(`  & Parameters<typeof $${filenameHashes[i]}.createRoute>[0]`);
	}

	writeLn(`
export function createApiRouter(router: Router, deps: AllRouteDeps) {`);

	const routeRe = /^\.\/(.*)$/;
	const routeParamsRe = /\[(\w+)\]/g;
	for (let i = 0; i < files.length; i++) {
		const routeParams = [...files[i].matchAll(routeParamsRe)].map((m) => m[1]);
		const route = files[i]
			.replace(routeRe, "/api/$1")
			.replace(routeParamsRe, ":$1");
		const typeProps = routeParams.map((p) => `${p}: string`).join("; ");

		writeLn(`
  {
    type Params = { ${typeProps} };
    const r: Route<Params> = $${filenameHashes[i]}.createRoute(deps);

    router.get("${route}", toQueryHandler(r.GET));
    router.post("${route}", toMutationHandler(r.POST));
    router.put("${route}", toMutationHandler(r.PUT));
    router.delete("${route}", toQueryHandler(r.DELETE));
  }`);
	}

	writeLn(`
  // Setup Swagger documentation
  setupSwagger(router);
}`);

	// Adding the server setup to the generated index file
	writeLn(`
const app = express();
const server = http.createServer(app);
const io = new Server(server);
const port = process.env.PORT || 5173;

const productionDomain = "https://app.squaredmade.com";
const productionServerDomain = "https://api.squaredmade.com"
const developmentDomain = "https://app-develop.squaredmade.com"
const localDevDomain = "http://localhost:3000";
const localServerDomain = \`http://localhost:\${port}\`;

// Health check route for root path
app.get("/", (_, res) => {
  res.status(200).send("ok");
});

app.use(
	cors({
		origin: (origin, callback) => {
			// Allow requests from Vercel branch deployments, production domain, and local development
			if (
				!origin ||
				${vercelRegex}.test(origin) ||
				origin === productionDomain ||
				origin === productionServerDomain ||
				origin === developmentDomain ||
				origin === localDevDomain ||
				origin === localServerDomain 
			) {
				callback(null, true);
			} else {
				callback(new Error("Not allowed by CORS"));
			}
		},
		methods: ["GET", "POST", "PUT", "DELETE"],
		credentials: true, // Allows credentials to be sent in requests
	}),
);

app.use(express.json());

const rpcRequestHandler = createRequestHandler(Object.values(rpcHandlers));
app.use("/rpc", rpcRequestHandler);

// Use the RPC error handler
app.use(createErrorHandler({ log: logger }));

// Initialize the router
const router = express.Router();

// Create the API router
createApiRouter(router, { prisma });

// Use the router
app.use(router);

// Socket.IO setup
io.on('connection', (socket) => {
  logger.info('A user connected');

  socket.on('joinRoom', (sprintId) => {
    socket.join(sprintId);
	logger.info('User joined room: %s', sprintId);
  });

  socket.on('addItem', (data) => {
    io.to(data.sprintId).emit('itemAdded', data);
  });

  socket.on('moveItem', (data) => {
    io.to(data.sprintId).emit('itemMoved', data);
  });

  socket.on('disconnect', () => {
    logger.info('User disconnected');
  });
});

// Start the server
server.listen(port, () => {
  logger.info(\`Server is running on http://localhost:\${port}\`);
});
`);
}

const logger = createCustomLogger("gen-index");

function getRoutes(dir: string): string[] {
	const files = fs.readdirSync(dir);
	const routes: string[] = [];

	logger.info("Checking directory: %s", dir);

	files.sort().reverse();

	for (const file of files) {
		const path = `${dir}/${file}`;
		const stat = fs.statSync(path);
		if (stat.isDirectory()) {
			routes.push(...getRoutes(path));
		} else if (path.endsWith("/index.ts")) {
			logger.info("Found route: %s", path);
			routes.push(path.replace("/index.ts", ""));
		}
	}
	return routes;
}

// Call the function to generate the index
generateIndex();

logger.info("Index file generated at: %s", outputPath);
