import fs from "node:fs";
import path from "node:path";
import "dotenv/config";
import createCustomLogger from "@squared/logger";

const logger = createCustomLogger("gen-index");
const outputPath = path.join(__dirname, "generated-routes.ts");

export function generateRoutes() {
	const routes = getRoutes(__dirname).sort();
	const content = generateRouteContent(routes);
	fs.writeFileSync(outputPath, content);
	logger.info("Routes file generated at: %s", outputPath);
}

function getRoutes(dir: string): string[] {
	const files = fs.readdirSync(dir);
	const routes: string[] = [];

	for (const file of files) {
		const filePath = path.join(dir, file);
		const stat = fs.statSync(filePath);
		if (stat.isDirectory()) {
			routes.push(...getRoutes(filePath));
		} else if (file === "index.ts") {
			routes.push(dir);
		}
	}

	return routes;
}

function generateRouteContent(routes: string[]): string {
	let content = `
// Code generated by generate-index.ts, DO NOT EDIT.
// @ts-nocheck

import type { Router } from "express";
import { toQueryHandler, toMutationHandler } from "./route";
import type { Route } from "./route";
`;

	const imports: string[] = [];
	const routeSetups: string[] = [];

	routes.forEach((route, index) => {
		const moduleName = `route${index}`;
		const relativePath = path.relative(__dirname, route).replace(/\\/g, "/");
		imports.push(`import * as ${moduleName} from "./${relativePath}";`);

		const routePath = `/${relativePath.replace(/\[(\w+)\]/g, ":$1")}`;
		routeSetups.push(`
  {
    type Params = Parameters<typeof ${moduleName}.createRoute>[0];
    const r: Route<Params> = ${moduleName}.createRoute(deps);
    router.get("${routePath}", toQueryHandler(r.GET));
    router.post("${routePath}", toMutationHandler(r.POST));
    router.put("${routePath}", toMutationHandler(r.PUT));
    router.delete("${routePath}", toQueryHandler(r.DELETE));
  }`);
	});

	content += `${imports.join("\n")}\n\n`;
	content += `export type AllRouteDeps = ${routes.map((_, i) => `Parameters<typeof route${i}.createRoute>[0]`).join(" & ")};\n\n`;
	content += `export function createApiRouter(router: Router, deps: AllRouteDeps) {${routeSetups.join("")}\n}\n`;

	return content;
}

generateRoutes();
