import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import "dotenv/config";
import createCustomLogger from "@squared/logger";

// Define the output path
const outputPath = path.join(__dirname, "generated-routes.ts");

// Ensure the file is empty before writing to it
fs.writeFileSync(outputPath, "");

// Generate the index and write to file
export function generateIndex() {
	const writeLn = (str: string) => fs.appendFileSync(outputPath, `${str}\n`);

	writeLn(`// Code generated by generate-index.ts, DO NOT EDIT.

import type { Router } from "express";
import { setupSwagger } from "../../swagger";
import { toMutationHandler, toQueryHandler } from "./route";
import type { Route } from "./route";

`);

	const files = getRoutes(__dirname)
		.map((p) => p.replace(__dirname, "."))
		.filter((p) => p !== ".");

	// Sort files to ensure consistent order
	files.sort();

	for (let i = 0; i < files.length; i++) {
		const hash = createRouteHash(files[i]);
		writeLn(`import * as ${hash} from "${files[i]}";`);
	}

	writeLn("\nexport type AllRouteDeps =");
	for (let i = 0; i < files.length; i++) {
		const hash = createRouteHash(files[i]);
		writeLn(`  & Parameters<typeof ${hash}.createRoute>[0]`);
	}

	writeLn(`
export function createApiRouter(router: Router, deps: AllRouteDeps) {`);

	const routeRe = /^\.\/(.*)$/;
	const routeParamsRe = /\[(\w+)\]/g;
	for (let i = 0; i < files.length; i++) {
		const routeParams = [...files[i].matchAll(routeParamsRe)].map((m) => m[1]);
		const route = files[i]
			.replace(routeRe, "/api/$1")
			.replace(routeParamsRe, ":$1");
		const typeProps = routeParams.map((p) => `${p}: string`).join("; ");
		const hash = createRouteHash(files[i]);

		writeLn(`
  {
    type Params = { ${typeProps} };
    const r: Route<Params> = ${hash}.createRoute(deps);

    router.get("${route}", toQueryHandler(r.GET));
    router.post("${route}", toMutationHandler(r.POST));
    router.put("${route}", toMutationHandler(r.PUT));
    router.delete("${route}", toQueryHandler(r.DELETE));
  }`);
	}

	writeLn(`
  // Setup Swagger documentation
   if (process.env.NODE_ENV !== 'test') {
    setupSwagger(router);
  }
}`);
}

const logger = createCustomLogger("gen-index");

function getRoutes(dir: string): string[] {
	const files = fs.readdirSync(dir);
	const routes: string[] = [];

	logger.info("Checking directory: %s", dir);

	for (const file of files) {
		const path = `${dir}/${file}`;
		const stat = fs.statSync(path);
		if (stat.isDirectory()) {
			routes.push(...getRoutes(path));
		} else if (path.endsWith("/index.ts")) {
			logger.info("Found route: %s", path);
			routes.push(path.replace("/index.ts", ""));
		}
	}
	return routes;
}

function createRouteHash(route: string): string {
	// Create a deterministic hash based on the route name
	const hash = createHash("sha256").update(route).digest("hex").slice(0, 8);
	return `route_${hash}`;
}

// Call the function to generate the index
generateIndex();

logger.info("Index file generated at: %s", outputPath);
