// Code generated by generate-index.ts, DO NOT EDIT.
// @ts-nocheck

import type { Router } from "express";
import { setupSwagger } from "../../swagger";
import { toMutationHandler, toQueryHandler } from "./route";
import type { Route } from "./route";

import * as $20ac97 from "./auth";
import * as $b27241 from "./auth/[token]";
import * as $8a4d33 from "./auth/logout";
import * as $dee49e from "./auth/reset-password";
import * as $725220 from "./auth/reset-password/[token]";
import * as $e36540 from "./filter/[filterId]";
import * as $8b611e from "./integration/github/oauth";
import * as $bbf840 from "./integration/github/webhook";
import * as $0a9f89 from "./team/[teamId]";
import * as $d8d9aa from "./user/[userId]";
import * as $bd3df0 from "./user/[userId]/avatar";
import * as $31d753 from "./user/[userId]/notification";
import * as $f96059 from "./user/[userId]/repositories";
import * as $c2e2ce from "./user/[userId]/team";
import * as $07572a from "./user/[userId]/workspace";
import * as $01aef2 from "./workspace/[workspaceId]";
import * as $0c244a from "./workspace/[workspaceId]/filter";
import * as $797fc8 from "./workspace/[workspaceId]/invite";
import * as $c29ed4 from "./workspace/[workspaceId]/label";
import * as $230080 from "./workspace/[workspaceId]/team";
import * as $2d5459 from "./workspace/[workspaceId]/user";
import * as $0daf92 from "./workspace/join";

export type AllRouteDeps = Parameters<typeof $0daf92.createRoute>[0] &
	Parameters<typeof $2d5459.createRoute>[0] &
	Parameters<typeof $230080.createRoute>[0] &
	Parameters<typeof $c29ed4.createRoute>[0] &
	Parameters<typeof $797fc8.createRoute>[0] &
	Parameters<typeof $01aef2.createRoute>[0] &
	Parameters<typeof $0c244a.createRoute>[0] &
	Parameters<typeof $07572a.createRoute>[0] &
	Parameters<typeof $c2e2ce.createRoute>[0] &
	Parameters<typeof $f96059.createRoute>[0] &
	Parameters<typeof $31d753.createRoute>[0] &
	Parameters<typeof $d8d9aa.createRoute>[0] &
	Parameters<typeof $bd3df0.createRoute>[0] &
	Parameters<typeof $0a9f89.createRoute>[0] &
	Parameters<typeof $bbf840.createRoute>[0] &
	Parameters<typeof $8b611e.createRoute>[0] &
	Parameters<typeof $e36540.createRoute>[0] &
	Parameters<typeof $dee49e.createRoute>[0] &
	Parameters<typeof $725220.createRoute>[0] &
	Parameters<typeof $8a4d33.createRoute>[0] &
	Parameters<typeof $20ac97.createRoute>[0] &
	Parameters<typeof $b27241.createRoute>[0];

export function createApiRouter(router: Router, deps: AllRouteDeps) {
	{
		type Params = {};
		const r: Route<Params> = $0daf92.createRoute(deps);

		router.get("/api/workspace/join", toQueryHandler(r.GET));
		router.post("/api/workspace/join", toMutationHandler(r.POST));
		router.put("/api/workspace/join", toMutationHandler(r.PUT));
		router.delete("/api/workspace/join", toQueryHandler(r.DELETE));
	}

	{
		type Params = { workspaceId: string };
		const r: Route<Params> = $2d5459.createRoute(deps);

		router.get("/api/workspace/:workspaceId/user", toQueryHandler(r.GET));
		router.post("/api/workspace/:workspaceId/user", toMutationHandler(r.POST));
		router.put("/api/workspace/:workspaceId/user", toMutationHandler(r.PUT));
		router.delete("/api/workspace/:workspaceId/user", toQueryHandler(r.DELETE));
	}

	{
		type Params = { workspaceId: string };
		const r: Route<Params> = $230080.createRoute(deps);

		router.get("/api/workspace/:workspaceId/team", toQueryHandler(r.GET));
		router.post("/api/workspace/:workspaceId/team", toMutationHandler(r.POST));
		router.put("/api/workspace/:workspaceId/team", toMutationHandler(r.PUT));
		router.delete("/api/workspace/:workspaceId/team", toQueryHandler(r.DELETE));
	}

	{
		type Params = { workspaceId: string };
		const r: Route<Params> = $c29ed4.createRoute(deps);

		router.get("/api/workspace/:workspaceId/label", toQueryHandler(r.GET));
		router.post("/api/workspace/:workspaceId/label", toMutationHandler(r.POST));
		router.put("/api/workspace/:workspaceId/label", toMutationHandler(r.PUT));
		router.delete(
			"/api/workspace/:workspaceId/label",
			toQueryHandler(r.DELETE),
		);
	}

	{
		type Params = { workspaceId: string };
		const r: Route<Params> = $797fc8.createRoute(deps);

		router.get("/api/workspace/:workspaceId/invite", toQueryHandler(r.GET));
		router.post(
			"/api/workspace/:workspaceId/invite",
			toMutationHandler(r.POST),
		);
		router.put("/api/workspace/:workspaceId/invite", toMutationHandler(r.PUT));
		router.delete(
			"/api/workspace/:workspaceId/invite",
			toQueryHandler(r.DELETE),
		);
	}

	{
		type Params = { workspaceId: string };
		const r: Route<Params> = $01aef2.createRoute(deps);

		router.get("/api/workspace/:workspaceId", toQueryHandler(r.GET));
		router.post("/api/workspace/:workspaceId", toMutationHandler(r.POST));
		router.put("/api/workspace/:workspaceId", toMutationHandler(r.PUT));
		router.delete("/api/workspace/:workspaceId", toQueryHandler(r.DELETE));
	}

	{
		type Params = { workspaceId: string };
		const r: Route<Params> = $0c244a.createRoute(deps);

		router.get("/api/workspace/:workspaceId/filter", toQueryHandler(r.GET));
		router.post(
			"/api/workspace/:workspaceId/filter",
			toMutationHandler(r.POST),
		);
		router.put("/api/workspace/:workspaceId/filter", toMutationHandler(r.PUT));
		router.delete(
			"/api/workspace/:workspaceId/filter",
			toQueryHandler(r.DELETE),
		);
	}

	{
		type Params = { userId: string };
		const r: Route<Params> = $07572a.createRoute(deps);

		router.get("/api/user/:userId/workspace", toQueryHandler(r.GET));
		router.post("/api/user/:userId/workspace", toMutationHandler(r.POST));
		router.put("/api/user/:userId/workspace", toMutationHandler(r.PUT));
		router.delete("/api/user/:userId/workspace", toQueryHandler(r.DELETE));
	}

	{
		type Params = { userId: string };
		const r: Route<Params> = $c2e2ce.createRoute(deps);

		router.get("/api/user/:userId/team", toQueryHandler(r.GET));
		router.post("/api/user/:userId/team", toMutationHandler(r.POST));
		router.put("/api/user/:userId/team", toMutationHandler(r.PUT));
		router.delete("/api/user/:userId/team", toQueryHandler(r.DELETE));
	}

	{
		type Params = { userId: string };
		const r: Route<Params> = $f96059.createRoute(deps);

		router.get("/api/user/:userId/repositories", toQueryHandler(r.GET));
		router.post("/api/user/:userId/repositories", toMutationHandler(r.POST));
		router.put("/api/user/:userId/repositories", toMutationHandler(r.PUT));
		router.delete("/api/user/:userId/repositories", toQueryHandler(r.DELETE));
	}

	{
		type Params = { userId: string };
		const r: Route<Params> = $31d753.createRoute(deps);

		router.get("/api/user/:userId/notification", toQueryHandler(r.GET));
		router.post("/api/user/:userId/notification", toMutationHandler(r.POST));
		router.put("/api/user/:userId/notification", toMutationHandler(r.PUT));
		router.delete("/api/user/:userId/notification", toQueryHandler(r.DELETE));
	}

	{
		type Params = { userId: string };
		const r: Route<Params> = $d8d9aa.createRoute(deps);

		router.get("/api/user/:userId", toQueryHandler(r.GET));
		router.post("/api/user/:userId", toMutationHandler(r.POST));
		router.put("/api/user/:userId", toMutationHandler(r.PUT));
		router.delete("/api/user/:userId", toQueryHandler(r.DELETE));
	}

	{
		type Params = { userId: string };
		const r: Route<Params> = $bd3df0.createRoute(deps);

		router.get("/api/user/:userId/avatar", toQueryHandler(r.GET));
		router.post("/api/user/:userId/avatar", toMutationHandler(r.POST));
		router.put("/api/user/:userId/avatar", toMutationHandler(r.PUT));
		router.delete("/api/user/:userId/avatar", toQueryHandler(r.DELETE));
	}

	{
		type Params = { teamId: string };
		const r: Route<Params> = $0a9f89.createRoute(deps);

		router.get("/api/team/:teamId", toQueryHandler(r.GET));
		router.post("/api/team/:teamId", toMutationHandler(r.POST));
		router.put("/api/team/:teamId", toMutationHandler(r.PUT));
		router.delete("/api/team/:teamId", toQueryHandler(r.DELETE));
	}

	{
		type Params = {};
		const r: Route<Params> = $bbf840.createRoute(deps);

		router.get("/api/integration/github/webhook", toQueryHandler(r.GET));
		router.post("/api/integration/github/webhook", toMutationHandler(r.POST));
		router.put("/api/integration/github/webhook", toMutationHandler(r.PUT));
		router.delete("/api/integration/github/webhook", toQueryHandler(r.DELETE));
	}

	{
		type Params = {};
		const r: Route<Params> = $8b611e.createRoute(deps);

		router.get("/api/integration/github/oauth", toQueryHandler(r.GET));
		router.post("/api/integration/github/oauth", toMutationHandler(r.POST));
		router.put("/api/integration/github/oauth", toMutationHandler(r.PUT));
		router.delete("/api/integration/github/oauth", toQueryHandler(r.DELETE));
	}

	{
		type Params = { filterId: string };
		const r: Route<Params> = $e36540.createRoute(deps);

		router.get("/api/filter/:filterId", toQueryHandler(r.GET));
		router.post("/api/filter/:filterId", toMutationHandler(r.POST));
		router.put("/api/filter/:filterId", toMutationHandler(r.PUT));
		router.delete("/api/filter/:filterId", toQueryHandler(r.DELETE));
	}

	{
		type Params = {};
		const r: Route<Params> = $dee49e.createRoute(deps);

		router.get("/api/auth/reset-password", toQueryHandler(r.GET));
		router.post("/api/auth/reset-password", toMutationHandler(r.POST));
		router.put("/api/auth/reset-password", toMutationHandler(r.PUT));
		router.delete("/api/auth/reset-password", toQueryHandler(r.DELETE));
	}

	{
		type Params = { token: string };
		const r: Route<Params> = $725220.createRoute(deps);

		router.get("/api/auth/reset-password/:token", toQueryHandler(r.GET));
		router.post("/api/auth/reset-password/:token", toMutationHandler(r.POST));
		router.put("/api/auth/reset-password/:token", toMutationHandler(r.PUT));
		router.delete("/api/auth/reset-password/:token", toQueryHandler(r.DELETE));
	}

	{
		type Params = {};
		const r: Route<Params> = $8a4d33.createRoute(deps);

		router.get("/api/auth/logout", toQueryHandler(r.GET));
		router.post("/api/auth/logout", toMutationHandler(r.POST));
		router.put("/api/auth/logout", toMutationHandler(r.PUT));
		router.delete("/api/auth/logout", toQueryHandler(r.DELETE));
	}

	{
		type Params = {};
		const r: Route<Params> = $20ac97.createRoute(deps);

		router.get("/api/auth", toQueryHandler(r.GET));
		router.post("/api/auth", toMutationHandler(r.POST));
		router.put("/api/auth", toMutationHandler(r.PUT));
		router.delete("/api/auth", toQueryHandler(r.DELETE));
	}

	{
		type Params = { token: string };
		const r: Route<Params> = $b27241.createRoute(deps);

		router.get("/api/auth/:token", toQueryHandler(r.GET));
		router.post("/api/auth/:token", toMutationHandler(r.POST));
		router.put("/api/auth/:token", toMutationHandler(r.PUT));
		router.delete("/api/auth/:token", toQueryHandler(r.DELETE));
	}

	// Setup Swagger documentation
	setupSwagger(router);
}
