// Code generated by generate-index.ts, DO NOT EDIT.
// @ts-nocheck
import express from "express";
import cors from "cors";
import type { Router } from "express";
import { toQueryHandler, toMutationHandler } from "./route";
import type { Route } from "./route";
import { PrismaClient } from "@repo/db";
import { setupSwagger } from "../swagger";
import { startSprintTransitionJob } from "@/jobs/scheduler";
import "dotenv/config";

startSprintTransitionJob();
export const prisma = new PrismaClient({
	datasources: {
		db: {
			url: process.env.POSTGRES_PRISMA_URL,
		},
	},
});

import * as $0daf92 from "./workspace/join";
import * as $2d5459 from "./workspace/[workspaceId]/user";
import * as $230080 from "./workspace/[workspaceId]/team";
import * as $c29ed4 from "./workspace/[workspaceId]/label";
import * as $797fc8 from "./workspace/[workspaceId]/invite";
import * as $01aef2 from "./workspace/[workspaceId]";
import * as $0c244a from "./workspace/[workspaceId]/filter";
import * as $07572a from "./user/[userId]/workspace";
import * as $31d753 from "./user/[userId]/notification";
import * as $d8d9aa from "./user/[userId]";
import * as $bd3df0 from "./user/[userId]/avatar";
import * as $61fb65 from "./team/[teamId]/task";
import * as $491871 from "./team/[teamId]/sprints";
import * as $e933fc from "./team/[teamId]/sprints/[sprintId]";
import * as $0a9f89 from "./team/[teamId]";
import * as $abb393 from "./task/[taskId]";
import * as $8f61d9 from "./task/[taskId]/comment";
import * as $5c5134 from "./notification";
import * as $302cff from "./notification/[notificationId]";
import * as $e36540 from "./filter/[filterId]";
import * as $97a568 from "./comment/[commentId]";
import * as $8a4d33 from "./auth/logout";
import * as $20ac97 from "./auth";
import * as $b27241 from "./auth/[token]";
import * as $5925fb from "./activity/[taskId]";

export type AllRouteDeps = Parameters<typeof $0daf92.createRoute>[0] &
	Parameters<typeof $2d5459.createRoute>[0] &
	Parameters<typeof $230080.createRoute>[0] &
	Parameters<typeof $c29ed4.createRoute>[0] &
	Parameters<typeof $797fc8.createRoute>[0] &
	Parameters<typeof $01aef2.createRoute>[0] &
	Parameters<typeof $0c244a.createRoute>[0] &
	Parameters<typeof $07572a.createRoute>[0] &
	Parameters<typeof $31d753.createRoute>[0] &
	Parameters<typeof $d8d9aa.createRoute>[0] &
	Parameters<typeof $bd3df0.createRoute>[0] &
	Parameters<typeof $61fb65.createRoute>[0] &
	Parameters<typeof $491871.createRoute>[0] &
	Parameters<typeof $e933fc.createRoute>[0] &
	Parameters<typeof $0a9f89.createRoute>[0] &
	Parameters<typeof $abb393.createRoute>[0] &
	Parameters<typeof $8f61d9.createRoute>[0] &
	Parameters<typeof $5c5134.createRoute>[0] &
	Parameters<typeof $302cff.createRoute>[0] &
	Parameters<typeof $e36540.createRoute>[0] &
	Parameters<typeof $97a568.createRoute>[0] &
	Parameters<typeof $8a4d33.createRoute>[0] &
	Parameters<typeof $20ac97.createRoute>[0] &
	Parameters<typeof $b27241.createRoute>[0] &
	Parameters<typeof $5925fb.createRoute>[0];

export function createApiRouter(router: Router, deps: AllRouteDeps) {
	{
		type Params = {};
		const r: Route<Params> = $0daf92.createRoute(deps);

		router.get("/api/workspace/join", toQueryHandler(r.GET));
		router.post("/api/workspace/join", toMutationHandler(r.POST));
		router.put("/api/workspace/join", toMutationHandler(r.PUT));
		router.delete("/api/workspace/join", toQueryHandler(r.DELETE));
	}

	{
		type Params = { workspaceId: string };
		const r: Route<Params> = $2d5459.createRoute(deps);

		router.get("/api/workspace/:workspaceId/user", toQueryHandler(r.GET));
		router.post("/api/workspace/:workspaceId/user", toMutationHandler(r.POST));
		router.put("/api/workspace/:workspaceId/user", toMutationHandler(r.PUT));
		router.delete("/api/workspace/:workspaceId/user", toQueryHandler(r.DELETE));
	}

	{
		type Params = { workspaceId: string };
		const r: Route<Params> = $230080.createRoute(deps);

		router.get("/api/workspace/:workspaceId/team", toQueryHandler(r.GET));
		router.post("/api/workspace/:workspaceId/team", toMutationHandler(r.POST));
		router.put("/api/workspace/:workspaceId/team", toMutationHandler(r.PUT));
		router.delete("/api/workspace/:workspaceId/team", toQueryHandler(r.DELETE));
	}

	{
		type Params = { workspaceId: string };
		const r: Route<Params> = $c29ed4.createRoute(deps);

		router.get("/api/workspace/:workspaceId/label", toQueryHandler(r.GET));
		router.post("/api/workspace/:workspaceId/label", toMutationHandler(r.POST));
		router.put("/api/workspace/:workspaceId/label", toMutationHandler(r.PUT));
		router.delete(
			"/api/workspace/:workspaceId/label",
			toQueryHandler(r.DELETE),
		);
	}

	{
		type Params = { workspaceId: string };
		const r: Route<Params> = $797fc8.createRoute(deps);

		router.get("/api/workspace/:workspaceId/invite", toQueryHandler(r.GET));
		router.post(
			"/api/workspace/:workspaceId/invite",
			toMutationHandler(r.POST),
		);
		router.put("/api/workspace/:workspaceId/invite", toMutationHandler(r.PUT));
		router.delete(
			"/api/workspace/:workspaceId/invite",
			toQueryHandler(r.DELETE),
		);
	}

	{
		type Params = { workspaceId: string };
		const r: Route<Params> = $01aef2.createRoute(deps);

		router.get("/api/workspace/:workspaceId", toQueryHandler(r.GET));
		router.post("/api/workspace/:workspaceId", toMutationHandler(r.POST));
		router.put("/api/workspace/:workspaceId", toMutationHandler(r.PUT));
		router.delete("/api/workspace/:workspaceId", toQueryHandler(r.DELETE));
	}

	{
		type Params = { workspaceId: string };
		const r: Route<Params> = $0c244a.createRoute(deps);

		router.get("/api/workspace/:workspaceId/filter", toQueryHandler(r.GET));
		router.post(
			"/api/workspace/:workspaceId/filter",
			toMutationHandler(r.POST),
		);
		router.put("/api/workspace/:workspaceId/filter", toMutationHandler(r.PUT));
		router.delete(
			"/api/workspace/:workspaceId/filter",
			toQueryHandler(r.DELETE),
		);
	}

	{
		type Params = { userId: string };
		const r: Route<Params> = $07572a.createRoute(deps);

		router.get("/api/user/:userId/workspace", toQueryHandler(r.GET));
		router.post("/api/user/:userId/workspace", toMutationHandler(r.POST));
		router.put("/api/user/:userId/workspace", toMutationHandler(r.PUT));
		router.delete("/api/user/:userId/workspace", toQueryHandler(r.DELETE));
	}

	{
		type Params = { userId: string };
		const r: Route<Params> = $31d753.createRoute(deps);

		router.get("/api/user/:userId/notification", toQueryHandler(r.GET));
		router.post("/api/user/:userId/notification", toMutationHandler(r.POST));
		router.put("/api/user/:userId/notification", toMutationHandler(r.PUT));
		router.delete("/api/user/:userId/notification", toQueryHandler(r.DELETE));
	}

	{
		type Params = { userId: string };
		const r: Route<Params> = $d8d9aa.createRoute(deps);

		router.get("/api/user/:userId", toQueryHandler(r.GET));
		router.post("/api/user/:userId", toMutationHandler(r.POST));
		router.put("/api/user/:userId", toMutationHandler(r.PUT));
		router.delete("/api/user/:userId", toQueryHandler(r.DELETE));
	}

	{
		type Params = { userId: string };
		const r: Route<Params> = $bd3df0.createRoute(deps);

		router.get("/api/user/:userId/avatar", toQueryHandler(r.GET));
		router.post("/api/user/:userId/avatar", toMutationHandler(r.POST));
		router.put("/api/user/:userId/avatar", toMutationHandler(r.PUT));
		router.delete("/api/user/:userId/avatar", toQueryHandler(r.DELETE));
	}

	{
		type Params = { teamId: string };
		const r: Route<Params> = $61fb65.createRoute(deps);

		router.get("/api/team/:teamId/task", toQueryHandler(r.GET));
		router.post("/api/team/:teamId/task", toMutationHandler(r.POST));
		router.put("/api/team/:teamId/task", toMutationHandler(r.PUT));
		router.delete("/api/team/:teamId/task", toQueryHandler(r.DELETE));
	}

	{
		type Params = { teamId: string };
		const r: Route<Params> = $491871.createRoute(deps);

		router.get("/api/team/:teamId/sprints", toQueryHandler(r.GET));
		router.post("/api/team/:teamId/sprints", toMutationHandler(r.POST));
		router.put("/api/team/:teamId/sprints", toMutationHandler(r.PUT));
		router.delete("/api/team/:teamId/sprints", toQueryHandler(r.DELETE));
	}

	{
		type Params = { teamId: string; sprintId: string };
		const r: Route<Params> = $e933fc.createRoute(deps);

		router.get("/api/team/:teamId/sprints/:sprintId", toQueryHandler(r.GET));
		router.post(
			"/api/team/:teamId/sprints/:sprintId",
			toMutationHandler(r.POST),
		);
		router.put("/api/team/:teamId/sprints/:sprintId", toMutationHandler(r.PUT));
		router.delete(
			"/api/team/:teamId/sprints/:sprintId",
			toQueryHandler(r.DELETE),
		);
	}

	{
		type Params = { teamId: string };
		const r: Route<Params> = $0a9f89.createRoute(deps);

		router.get("/api/team/:teamId", toQueryHandler(r.GET));
		router.post("/api/team/:teamId", toMutationHandler(r.POST));
		router.put("/api/team/:teamId", toMutationHandler(r.PUT));
		router.delete("/api/team/:teamId", toQueryHandler(r.DELETE));
	}

	{
		type Params = { taskId: string };
		const r: Route<Params> = $abb393.createRoute(deps);

		router.get("/api/task/:taskId", toQueryHandler(r.GET));
		router.post("/api/task/:taskId", toMutationHandler(r.POST));
		router.put("/api/task/:taskId", toMutationHandler(r.PUT));
		router.delete("/api/task/:taskId", toQueryHandler(r.DELETE));
	}

	{
		type Params = { taskId: string };
		const r: Route<Params> = $8f61d9.createRoute(deps);

		router.get("/api/task/:taskId/comment", toQueryHandler(r.GET));
		router.post("/api/task/:taskId/comment", toMutationHandler(r.POST));
		router.put("/api/task/:taskId/comment", toMutationHandler(r.PUT));
		router.delete("/api/task/:taskId/comment", toQueryHandler(r.DELETE));
	}

	{
		type Params = {};
		const r: Route<Params> = $5c5134.createRoute(deps);

		router.get("/api/notification", toQueryHandler(r.GET));
		router.post("/api/notification", toMutationHandler(r.POST));
		router.put("/api/notification", toMutationHandler(r.PUT));
		router.delete("/api/notification", toQueryHandler(r.DELETE));
	}

	{
		type Params = { notificationId: string };
		const r: Route<Params> = $302cff.createRoute(deps);

		router.get("/api/notification/:notificationId", toQueryHandler(r.GET));
		router.post("/api/notification/:notificationId", toMutationHandler(r.POST));
		router.put("/api/notification/:notificationId", toMutationHandler(r.PUT));
		router.delete(
			"/api/notification/:notificationId",
			toQueryHandler(r.DELETE),
		);
	}

	{
		type Params = { filterId: string };
		const r: Route<Params> = $e36540.createRoute(deps);

		router.get("/api/filter/:filterId", toQueryHandler(r.GET));
		router.post("/api/filter/:filterId", toMutationHandler(r.POST));
		router.put("/api/filter/:filterId", toMutationHandler(r.PUT));
		router.delete("/api/filter/:filterId", toQueryHandler(r.DELETE));
	}

	{
		type Params = { commentId: string };
		const r: Route<Params> = $97a568.createRoute(deps);

		router.get("/api/comment/:commentId", toQueryHandler(r.GET));
		router.post("/api/comment/:commentId", toMutationHandler(r.POST));
		router.put("/api/comment/:commentId", toMutationHandler(r.PUT));
		router.delete("/api/comment/:commentId", toQueryHandler(r.DELETE));
	}

	{
		type Params = {};
		const r: Route<Params> = $8a4d33.createRoute(deps);

		router.get("/api/auth/logout", toQueryHandler(r.GET));
		router.post("/api/auth/logout", toMutationHandler(r.POST));
		router.put("/api/auth/logout", toMutationHandler(r.PUT));
		router.delete("/api/auth/logout", toQueryHandler(r.DELETE));
	}

	{
		type Params = {};
		const r: Route<Params> = $20ac97.createRoute(deps);

		router.get("/api/auth", toQueryHandler(r.GET));
		router.post("/api/auth", toMutationHandler(r.POST));
		router.put("/api/auth", toMutationHandler(r.PUT));
		router.delete("/api/auth", toQueryHandler(r.DELETE));
	}

	{
		type Params = { token: string };
		const r: Route<Params> = $b27241.createRoute(deps);

		router.get("/api/auth/:token", toQueryHandler(r.GET));
		router.post("/api/auth/:token", toMutationHandler(r.POST));
		router.put("/api/auth/:token", toMutationHandler(r.PUT));
		router.delete("/api/auth/:token", toQueryHandler(r.DELETE));
	}

	{
		type Params = { taskId: string };
		const r: Route<Params> = $5925fb.createRoute(deps);

		router.get("/api/activity/:taskId", toQueryHandler(r.GET));
		router.post("/api/activity/:taskId", toMutationHandler(r.POST));
		router.put("/api/activity/:taskId", toMutationHandler(r.PUT));
		router.delete("/api/activity/:taskId", toQueryHandler(r.DELETE));
	}

	// Setup Swagger documentation
	setupSwagger(router);
}

const app = express();
const port = process.env.PORT || 5173;

const productionDomain = "https://app.squaredmade.com";
const productionServerDomain = "https://api.squaredmade.com";
const localDevDomain = "http://localhost:3000";
const localServerDomain = `http://localhost:${port}`;
// Health check route for root path
app.get("/", (_, res) => {
	res.status(200).send("ok");
});

app.use(
	cors({
		origin: (origin, callback) => {
			// Allow requests from Vercel branch deployments, production domain, and local development
			if (
				!origin ||
				/^https:\/\/web-(\w+)-squaredmade\.vercel\.app$/.test(origin) ||
				origin === productionDomain ||
				orgin === productionServerDomain ||
				origin === localDevDomain ||
				origin === localServerDomain
			) {
				callback(null, true);
			} else {
				callback(new Error("Not allowed by CORS"));
			}
		},
		methods: ["GET", "POST", "PUT", "DELETE"],
		credentials: true, // Allows credentials to be sent in requests
	}),
);

app.use(express.json());

// Initialize the router
const router = express.Router();

// Create the API router
createApiRouter(router, { prisma });

// Use the router
app.use(router);

// Start the server
app.listen(port, () => {
	console.log(`Server is running on http://localhost:${port}`);
});
