// Code generated by generate-index.ts, DO NOT EDIT.

import { rpcHandlers } from "@/services";
import { createDb } from "@squared/db";
import createCustomLogger from "@squared/logger";
import { createErrorHandler, createRequestHandler } from "@squared/rpc";
import cors from "cors";
import "dotenv/config";
import http from "node:http";
import express from "express";
import { Server } from "socket.io";
import { createApiRouter } from "./generated-routes";

export const db = createDb({ databaseUrl: process.env.DATABASE_URL });

const logger = createCustomLogger("api");

const app = express();
const server = http.createServer(app);
const io = new Server(server);
const port = process.env.PORT || 5173;

const productionDomain = "https://app.squaredmade.com";
const productionServerDomain = "https://api.squaredmade.com";
const developmentDomain = "https://app-develop.squaredmade.com";
const localDevDomain = "http://localhost:3000";
const localServerDomain = `http://localhost:${port}`;

// Health check route for root path
app.get("/", (_, res) => {
	res.status(200).send("ok");
});

app.use(
	cors({
		origin: (origin, callback) => {
			// Allow requests from Vercel branch deployments, production domain, and local development
			if (
				!origin ||
				/^https:\/\/web-(\w+)-squaredmade\.vercel\.app$/.test(origin) ||
				origin === productionDomain ||
				origin === productionServerDomain ||
				origin === developmentDomain ||
				origin === localDevDomain ||
				origin === localServerDomain
			) {
				callback(null, true);
			} else {
				callback(new Error("Not allowed by CORS"));
			}
		},
		methods: ["GET", "POST", "PUT", "DELETE"],
		credentials: true, // Allows credentials to be sent in requests
	}),
);

app.use(express.json());

const rpcRequestHandler = createRequestHandler(Object.values(rpcHandlers));
app.use("/rpc", rpcRequestHandler);

// Use the RPC error handler
app.use(createErrorHandler({ log: logger }));

// Initialize the router
const router = express.Router();

// Create the API router
createApiRouter(router, { db });

// Use the router
app.use(router);

// Socket.IO setup
io.on("connection", (socket) => {
	logger.info("A user connected");

	socket.on("joinRoom", (sprintId) => {
		socket.join(sprintId);
		logger.info("User joined room", sprintId);
	});

	socket.on("addItem", (data) => {
		io.to(data.sprintId).emit("itemAdded", data);
	});

	socket.on("moveItem", (data) => {
		io.to(data.sprintId).emit("itemMoved", data);
	});

	socket.on("disconnect", () => {
		logger.info("User disconnected");
	});
});

// Start the server
server.listen(port, () => {
	logger.info(`Server is running on http://localhost:${port}`);
});
