import fs from "node:fs";

const dir = __dirname.split("/");
const parentDir = dir.slice(0, dir.length - 1).join("/");
const prismaDir = `${parentDir}/prisma`;
const schemaOutputPath = `${prismaDir}/testing-schema.prisma`;

// clear existing schema
fs.writeFileSync(schemaOutputPath, "");

const writeLns = (path: string, ...lines: string[]) => {
	for (const line of lines) {
		fs.appendFileSync(path, `${line}\n`);
	}
};

const schema = String(fs.readFileSync(`${prismaDir}/schema.prisma`))
	.replace(
		'output   = "../generated/client"',
		'output   = "../generated/test-client"',
	)
	.replace(
		'url       = env("TEST_POSTGRES_PRISMA_URL")',
		'url       = env("TESTING_DB_POSTGRES_PRISMA_URL")',
	)
	.replace(
		'directUrl = env("TEST_POSTGRES_URL_NON_POOLING")',
		'directUrl = env("TESTING_DB_POSTGRES_URL_NON_POOLING")',
	);

writeLns(
	schemaOutputPath,
	`// Schema generated by generate-testing-schema.ts
// Do not edit this file as it is automatically overwritten whenever the test script is run.
//
// Multiple datasources using the same schema requires two different schema files.",
// See issue: https://github.com/prisma/prisma/issues/2443#issuecomment-630679118\n`,
	schema,
);

console.log("Created a mirrored schema for testing.");
