import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import "dotenv/config";

// Define the output path
const outputPath = path.join(__dirname, "index.ts");
const vercelRegex = /^https:\/\/web-production-(\w+)-squaredmade\.vercel\.app$/;

// Ensure the file is empty before writing to it
fs.writeFileSync(outputPath, "");

// Generate the index and write to file
export function generateIndex() {
	const writeLn = (str: string) => fs.appendFileSync(outputPath, `${str}\n`);

	writeLn(`// Code generated by generate-index.ts, DO NOT EDIT.
// @ts-nocheck
import express from "express";
import cors from "cors";
import type { Router } from "express";
import { toQueryHandler, toMutationHandler } from "./route";
import type { Route } from "./route";
${process.env.NODE_ENV === "test" ? `import { PrismaClient } from "@repo/test-db";` : `import { PrismaClient } from "@prisma/client";`}
import { setupSwagger } from "./swagger"; // Import Swagger setup
import "dotenv/config";

export const prisma = new PrismaClient();

`);

	const files = getRoutes(__dirname)
		.map((p) => p.replace(__dirname, "."))
		.filter((p) => p !== ".");

	const filenameHashes: string[] = [];

	for (let i = 0; i < files.length; i++) {
		const hash = createHash("sha1").update(files[i]).digest().subarray(-3);
		while (filenameHashes.includes(hash.toString("hex"))) {
			hash[0]++;
		}
		filenameHashes.push(hash.toString("hex"));

		writeLn(`import * as $${filenameHashes[i]} from "${files[i]}";`);
	}

	writeLn("\nexport type AllRouteDeps =");
	for (let i = 0; i < files.length; i++) {
		writeLn(`  & Parameters<typeof $${filenameHashes[i]}.createRoute>[0]`);
	}

	writeLn(`
export function createApiRouter(router: Router, deps: AllRouteDeps) {`);

	const routeRe = /^\.\/(.*)$/;
	const routeParamsRe = /\[(\w+)\]/g;
	for (let i = 0; i < files.length; i++) {
		const routeParams = [...files[i].matchAll(routeParamsRe)].map((m) => m[1]);
		const route = files[i]
			.replace(routeRe, "/api/$1")
			.replace(routeParamsRe, ":$1");
		const typeProps = routeParams.map((p) => `${p}: string`).join("; ");

		writeLn(`
  {
    type Params = { ${typeProps} };
    const r: Route<Params> = $${filenameHashes[i]}.createRoute(deps);

    router.get("${route}", toQueryHandler(r.GET));
    router.post("${route}", toMutationHandler(r.POST));
    router.put("${route}", toMutationHandler(r.PUT));
    router.delete("${route}", toQueryHandler(r.DELETE));
  }`);
	}

	writeLn(`
  // Setup Swagger documentation
  setupSwagger(router);
}`);

	// Adding the server setup to the generated index file
	writeLn(`
const app = express();
const port = process.env.PORT || 5173;

const productionDomain = "https://app.squaredmade.com";
const localDevDomain = "http://localhost:3000";

app.use(
	cors({
		origin: (origin, callback) => {
			// Allow requests from Vercel branch deployments, production domain, and local development
			if (
				!origin ||
				${vercelRegex}.test(origin) ||
				origin === productionDomain ||
				origin === localDevDomain
			) {
				callback(null, true);
			} else {
				callback(new Error("Not allowed by CORS"));
			}
		},
		methods: ["GET", "POST", "PUT", "DELETE"],
		credentials: true, // Allows credentials to be sent in requests
	}),
);

app.use(express.json());

// Initialize the router
const router = express.Router();

// Create the API router
createApiRouter(router, { prisma });

// Use the router
app.use(router);

// Start the server
app.listen(port, () => {
  console.log(\`Server is running on http://localhost:\${port}\`);
});
`);
}

function getRoutes(dir: string): string[] {
	const files = fs.readdirSync(dir);
	const routes: string[] = [];

	const blacklistedRoutes = ["docs", "utils"];

	console.log("Checking directory:", dir);

	files.sort().reverse();

	for (const file of files) {
		const path = `${dir}/${file}`;
		const stat = fs.statSync(path);
		if (stat.isDirectory()) {
			if (!blacklistedRoutes.includes(file)) {
				routes.push(...getRoutes(path));
			}
		} else if (path.endsWith("/index.ts")) {
			console.log("Found route:", path);
			routes.push(path.replace("/index.ts", ""));
		}
	}
	return routes;
}

// Call the function to generate the index
generateIndex();

console.log("Index file generated at:", outputPath);
