package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

const (
	configDir  = ".squared"
	configFile = "services.json"
)

type MethodInfo struct {
	MethodName     string    `json:"methodName"`
	ParamNames     []string  `json:"paramNames"`
	MethodTimeout  int       `json:"methodTimeout"`
	Help           string    `json:"help"`
	RequestSchema  ZodSchema `json:"requestSchema"`
	ResponseSchema ZodSchema `json:"responseSchema"`
	InputType      string    // Generated TypeScript type
	OutputType     string    // Generated TypeScript type
}

type Service struct {
	Name       string `json:"serviceName"`
	MultiArg   bool   `json:"multiArg"`
	Help       string `json:"help"`
	URL        string
	Interfaces []MethodInfo `json:"interfaces"`
}

type ZodSchema struct {
	Type       string               `json:"type"`
	Properties map[string]ZodSchema `json:"properties,omitempty"`
	Items      *ZodSchema           `json:"items,omitempty"`
	Values     []interface{}        `json:"values,omitempty"`
	Options    []ZodSchema          `json:"options,omitempty"`
	Value      interface{}          `json:"value,omitempty"`
	Inner      *ZodSchema           `json:"inner,omitempty"`
}

func installService(cmd *cobra.Command, args []string) {
	serviceURL := args[0]
	fmt.Printf("Installing service from URL: %s\n", serviceURL)

	// Fetch service information
	resp, err := http.Get(serviceURL)
	if err != nil {
		fmt.Printf("Error fetching service information: %v\n", err)
		return
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		fmt.Printf("Error reading service information: %v\n", err)
		return
	}

	var service Service
	err = json.Unmarshal(body, &service)
	if err != nil {
		fmt.Printf("Error parsing service information: %v\n", err)
		return
	}

	if service.Name == "" {
		fmt.Println("Error: Service name not found in the response")
		return
	}

	service.URL = serviceURL

	// Save service information
	services, err := loadServices()
	if err != nil {
		fmt.Printf("Error loading existing services: %v\n", err)
		return
	}

	// Check if service already exists
	for i, s := range services {
		if s.Name == service.Name {
			services[i] = service // Update existing service
			fmt.Printf("Service '%s' updated successfully\n", service.Name)
			err = saveServices(services)
			if err != nil {
				fmt.Printf("Error saving service information: %v\n", err)
				return
			}
			generateTypeScriptFile(service)
			return
		}
	}

	// Add new service
	services = append(services, service)
	err = saveServices(services)
	if err != nil {
		fmt.Printf("Error saving service information: %v\n", err)
		return
	}

	fmt.Printf("Service '%s' installed successfully\n", service.Name)
	generateTypeScriptFile(service)
}

func listServices(cmd *cobra.Command, args []string) {
	fmt.Println("Listing all available services:")

	services, err := loadServices()
	if err != nil {
		fmt.Printf("Error loading services: %v\n", err)
		return
	}

	if len(services) == 0 {
		fmt.Println("No services installed")
		return
	}

	for _, service := range services {
		fmt.Printf("- %s\n", service.Name)
		fmt.Printf("  URL: %s\n", service.URL)
		if len(service.Interfaces) > 0 {
			fmt.Println("  Interfaces:")
			for _, iface := range service.Interfaces {
				fmt.Printf("    - %s\n", iface.MethodName)
			}
		}
		fmt.Println()
	}
}

func loadServices() ([]Service, error) {
	configPath := filepath.Join(os.Getenv("HOME"), ".squared", "services.json")
	data, err := os.ReadFile(configPath)
	if os.IsNotExist(err) {
		return []Service{}, nil
	} else if err != nil {
		return nil, err
	}

	var services []Service
	err = json.Unmarshal(data, &services)
	if err != nil {
		return nil, err
	}

	return services, nil
}

func saveServices(services []Service) error {
	configPath := filepath.Join(os.Getenv("HOME"), ".squared", "services.json")
	data, err := json.MarshalIndent(services, "", "  ")
	if err != nil {
		return err
	}

	err = os.MkdirAll(filepath.Dir(configPath), 0755)
	if err != nil {
		return err
	}

	return os.WriteFile(configPath, data, 0644)
}

func generateTypeScriptFile(service Service) {
	cwd, err := os.Getwd()
	if err != nil {
		fmt.Printf("Error getting current working directory: %v\n", err)
		return
	}

	genDir := filepath.Join(cwd, "gen", "rpc")
	err = os.MkdirAll(genDir, 0755)
	if err != nil {
		fmt.Printf("Error creating directory: %v\n", err)
		return
	}

	fileName := filepath.Join(genDir, fmt.Sprintf("%s.ts", strings.ToLower(service.Name)))

	funcMap := template.FuncMap{
		"toPascalCase": toPascalCase,
	}

	tmpl := template.Must(template.New("typescript").Funcs(funcMap).Parse(`
// Code generated by @squared/cli, DO NOT EDIT.
import { RPCContextClient } from "@squared/rpc-client";
import type { Context } from "@squared/context";

{{range .Interfaces}}
{{if ne .InputType "void"}}
export type {{toPascalCase .MethodName}}Request = {{.InputType}};
{{end}}

{{if ne .OutputType "void"}}
export type {{toPascalCase .MethodName}}Response = {{.OutputType}};
{{end}}

{{end}}

/**
 * {{.Name}} service
 */
export class {{toPascalCase .Name}}Service extends RPCContextClient {
  constructor(baseUrl: string) {
    super(baseUrl, "{{.Name}}");
  }
  {{range .Interfaces}}
  /**
   * {{.MethodName}} method
   */
  {{.MethodName}}(ctx: Context, req: {{if eq .InputType "void"}}void{{else}}{{toPascalCase .MethodName}}Request{{end}}): Promise<{{if eq .OutputType "void"}}void{{else}}{{toPascalCase .MethodName}}Response{{end}}> {
    return this.request(ctx, "{{.MethodName}}", req);
  }
  {{end}}
}
`))

	file, err := os.Create(fileName)
	if err != nil {
		fmt.Printf("Error creating file: %v\n", err)
		return
	}
	defer file.Close()

	for i, iface := range service.Interfaces {
		service.Interfaces[i].InputType = zodToTypeScript(iface.RequestSchema)
		service.Interfaces[i].OutputType = zodToTypeScript(iface.ResponseSchema)
	}

	err = tmpl.Execute(file, service)
	if err != nil {
		fmt.Printf("Error generating TypeScript file: %v\n", err)
		return
	}

	fmt.Printf("Generated TypeScript file: %s\n", fileName)

	// Try running Biome and suppress unnecessary errors
	runBiomeFormat(fileName)
}

func runBiomeFormat(fileName string) {
	cmd := exec.Command("pnpm", "format:write", fileName)
	err := cmd.Run()
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			// Suppress the error if it's related to no files being changed
			if strings.Contains(string(exitErr.Stderr), "No files were processed") {
				fmt.Println("Biome did not apply any changes, skipping error")
				return
			}
		}
		fmt.Printf("Error running biome format: %v\n", err)
	} else {
		fmt.Printf("Biome formatting applied to: %s\n", fileName)
	}
}

func zodToTypeScript(schema ZodSchema) string {
	switch schema.Type {
	case "object":
		props := []string{}
		keys := make([]string, 0, len(schema.Properties))
		for key := range schema.Properties {
			keys = append(keys, key)
		}
		sort.Strings(keys) // Ensure keys are sorted alphabetically

		for _, key := range keys {
			value := schema.Properties[key]
			propType := zodToTypeScript(value)
			optionalPrefix := ""
			if value.Type == "optional" {
				optionalPrefix = "?"
				propType = zodToTypeScript(*value.Inner)
			}
			// Add a newline and indentation for each property
			props = append(props, fmt.Sprintf("\t%s%s: %s;", key, optionalPrefix, propType))
		}
		if len(props) == 0 {
			return "Record<string, unknown>"
		}
		return fmt.Sprintf("{\n%s\n}", strings.Join(props, "\n"))
	case "array":
		if schema.Items != nil {
			elementType := zodToTypeScript(*schema.Items)
			return fmt.Sprintf("%s[]", elementType)
		}
		return "unknown[]"
	case "string":
		return "string"
	case "number":
		return "number"
	case "boolean":
		return "boolean"
	case "date":
		return "Date"
	case "enum":
		if len(schema.Values) > 0 {
			enumValues := make([]string, len(schema.Values))
			for i, v := range schema.Values {
				enumValues[i] = fmt.Sprintf("\"%v\"", v)
			}
			return strings.Join(enumValues, " | ")
		}
		return "unknown"
	case "union":
		unionTypes := make([]string, len(schema.Options))
		for i, option := range schema.Options {
			unionTypes[i] = zodToTypeScript(option)
		}
		return fmt.Sprintf("(%s)", strings.Join(unionTypes, " | "))
	case "literal":
		if schema.Value != nil {
			return fmt.Sprintf("\"%v\"", schema.Value)
		}
		return "unknown"
	case "nullable":
		if schema.Inner != nil {
			return fmt.Sprintf("%s | null", zodToTypeScript(*schema.Inner))
		}
		return "null | unknown"
	case "optional":
		if schema.Inner != nil {
			return zodToTypeScript(*schema.Inner)
		}
		return "unknown | undefined"
	case "void":
		return "void"
	case "null":
		return "null"
	case "undefined":
		return "undefined"
	default:
		return "unknown"
	}
}

func toPascalCase(s string) string {
	if len(s) == 0 {
		return s
	}

	// Capitalize the first letter, leave the rest unchanged
	return strings.ToUpper(string(s[0])) + s[1:]
}
