package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

const (
	configDir  = ".squared"
	configFile = "services.json"
)

type MethodInfo struct {
	MethodName    string    `json:"methodName"`
	ParamNames    []string  `json:"paramNames"`
	MethodTimeout int       `json:"methodTimeout"`
	Help          string    `json:"help"`
	RequestSchema ZodSchema `json:"requestSchema"`
	ResponseSchema ZodSchema `json:"responseSchema"`
	InputType     string    // Generated TypeScript type
	OutputType    string    // Generated TypeScript type
}

type Service struct {
	Name       string       `json:"serviceName"`
	MultiArg   bool         `json:"multiArg"`
	Help       string       `json:"help"`
	URL        string
	Interfaces []MethodInfo `json:"interfaces"`
}

type ZodSchema struct {
	Def struct {
		TypeName    string                 `json:"typeName"`
		Type        *ZodSchema             `json:"type,omitempty"`
		Shape       map[string]*ZodSchema  `json:"shape,omitempty"`
		Options     []ZodSchema            `json:"options,omitempty"`
		UnknownKeys string                 `json:"unknownKeys,omitempty"`
		Catchall    map[string]interface{} `json:"catchall,omitempty"`
	} `json:"_def"`
}

func installService(cmd *cobra.Command, args []string) {
	serviceURL := args[0]
	fmt.Printf("Installing service from URL: %s\n", serviceURL)

	// Fetch service information
	resp, err := http.Get(serviceURL)
	if err != nil {
		fmt.Printf("Error fetching service information: %v\n", err)
		return
	}
	defer resp.Body.Close()

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		fmt.Printf("Error reading service information: %v\n", err)
		return
	}

	fmt.Printf("Debug: Raw response: %s\n", string(body))

	var service Service
	err = json.Unmarshal(body, &service)
	if err != nil {
		fmt.Printf("Error parsing service information: %v\n", err)
		return
	}

	if service.Name == "" {
		fmt.Println("Error: Service name not found in the response")
		return
	}

	service.URL = serviceURL

	// Save service information
	services, err := loadServices()
	if err != nil {
		fmt.Printf("Error loading existing services: %v\n", err)
		return
	}

	// Check if service already exists
	for i, s := range services {
		if s.Name == service.Name {
			services[i] = service // Update existing service
			fmt.Printf("Service '%s' updated successfully\n", service.Name)
			err = saveServices(services)
			if err != nil {
				fmt.Printf("Error saving service information: %v\n", err)
				return
			}
			generateTypeScriptFile(service)
			return
		}
	}

	// Add new service
	services = append(services, service)
	err = saveServices(services)
	if err != nil {
		fmt.Printf("Error saving service information: %v\n", err)
		return
	}

	fmt.Printf("Service '%s' installed successfully\n", service.Name)
	generateTypeScriptFile(service)
}

func listServices(cmd *cobra.Command, args []string) {
	fmt.Println("Listing all available services:")

	services, err := loadServices()
	if err != nil {
		fmt.Printf("Error loading services: %v\n", err)
		return
	}

	if len(services) == 0 {
		fmt.Println("No services installed")
		return
	}

	for _, service := range services {
		fmt.Printf("- %s\n", service.Name)
		fmt.Printf("  URL: %s\n", service.URL)
		if len(service.Interfaces) > 0 {
			fmt.Println("  Interfaces:")
			for _, iface := range service.Interfaces {
				fmt.Printf("    - %s\n", iface.MethodName)
			}
		}
		fmt.Println()
	}
}

func loadServices() ([]Service, error) {
	configPath := filepath.Join(os.Getenv("HOME"), ".squared", "services.json")
	data, err := ioutil.ReadFile(configPath)
	if os.IsNotExist(err) {
		return []Service{}, nil
	} else if err != nil {
		return nil, err
	}

	var services []Service
	err = json.Unmarshal(data, &services)
	if err != nil {
		return nil, err
	}

	return services, nil
}

func saveServices(services []Service) error {
	configPath := filepath.Join(os.Getenv("HOME"), ".squared", "services.json")
	data, err := json.MarshalIndent(services, "", "  ")
	if err != nil {
		return err
	}

	err = os.MkdirAll(filepath.Dir(configPath), 0755)
	if err != nil {
		return err
	}

	return ioutil.WriteFile(configPath, data, 0644)
}

func generateTypeScriptFile(service Service) {
	cwd, err := os.Getwd()
	if err != nil {
		fmt.Printf("Error getting current working directory: %v\n", err)
		return
	}

	genDir := filepath.Join(cwd, "gen", "rpc")
	err = os.MkdirAll(genDir, 0755)
	if err != nil {
		fmt.Printf("Error creating directory: %v\n", err)
		return
	}

	fileName := filepath.Join(genDir, fmt.Sprintf("%s.ts", strings.ToLower(service.Name)))

	tmpl := template.Must(template.New("typescript").Parse(`
// Code generated by squared-cli, DO NOT EDIT.
/* eslint-disable */
import { RPCContextClient } from "@squared/http-rpc-client";
import { Context } from "@squared/context";

{{range .Interfaces}}
export type {{.MethodName}}Request = {{.InputType}};

export type {{.MethodName}}Response = {{.OutputType}};

{{end}}

/**
 * {{.Name}} service
 */
export class {{.Name}}Service extends RPCContextClient {
  constructor(baseUrl: string) {
    super(baseUrl, "{{.Name}}");
  }
  {{range .Interfaces}}
  /**
   * {{.MethodName}} method
   */
  {{.MethodName}}(ctx: Context, req: {{.MethodName}}Request): Promise<{{.MethodName}}Response> {
    return this.request(ctx, "{{.MethodName}}", req);
  }
  {{end}}
}
`))

	file, err := os.Create(fileName)
	if err != nil {
		fmt.Printf("Error creating file: %v\n", err)
		return
	}
	defer file.Close()

	for i, iface := range service.Interfaces {
		fmt.Printf("Debug: Processing method %s\n", iface.MethodName)
		
		service.Interfaces[i].InputType = zodToTypeScript(iface.RequestSchema)
		service.Interfaces[i].OutputType = zodToTypeScript(iface.ResponseSchema)

		fmt.Printf("Debug: Generated input type: %s\n", service.Interfaces[i].InputType)
		fmt.Printf("Debug: Generated output type: %s\n", service.Interfaces[i].OutputType)
	}

	err = tmpl.Execute(file, service)
	if err != nil {
		fmt.Printf("Error generating TypeScript file: %v\n", err)
		return
	}

	fmt.Printf("Generated TypeScript file: %s\n", fileName)
}

func zodToTypeScript(schema ZodSchema) string {
	switch schema.Def.TypeName {
	case "ZodObject":
		properties := []string{}
		for key, value := range schema.Def.Shape {
			if value != nil {
				subType := zodToTypeScript(*value)
				properties = append(properties, fmt.Sprintf("%s: %s", key, subType))
			}
		}
		if len(properties) == 0 {
			return "Record<string, unknown>"
		}
		return fmt.Sprintf("{ %s }", strings.Join(properties, "; "))
	case "ZodArray":
		if schema.Def.Type != nil {
			elementType := zodToTypeScript(*schema.Def.Type)
			return fmt.Sprintf("%s[]", elementType)
		}
		return "unknown[]"
	case "ZodString":
		return "string"
	case "ZodNumber":
		return "number"
	case "ZodBoolean":
		return "boolean"
	case "ZodUnion":
		unionTypes := []string{}
		for _, option := range schema.Def.Options {
			unionType := zodToTypeScript(option)
			unionTypes = append(unionTypes, unionType)
		}
		return strings.Join(unionTypes, " | ")
	case "ZodVoid":
		return "void"
	case "ZodNever":
		return "never"
	default:
		return "unknown"
	}
}