// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion: dynamic(() => import("./Accordion")),
  bullet_points: dynamic(() => import("./Lists")),
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  link: dynamic(() => import("./Link")),
};
