// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bullet_points: dynamic(() => import("./Lists")),
  hero: dynamic(() => import("./Hero")),
};
