services:
  db:
    image: postgres:17
    container_name: postgres-test-db
    environment:
      POSTGRES_USER: squared
      POSTGRES_PASSWORD: squared
      POSTGRES_DB: squared-test
    ports:
      - "5433:5433"

  test:
    build:
      context: ../../.
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 5173:5173
    env_file: ./.env