name: Auto Assign PR to Author

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Apply Herald rules to auto-assign PR
        uses: gagoar/use-herald-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          rulesLocation: .github/herald_rules/auto-assign.json
