name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      SHELL: /bin/bash  # Explicitly set the shell

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Setup global bin directory for pnpm
        run: pnpm setup

      - name: Install Turbo globally (pinned to a specific version)
        run: npm i turbo@2 --global

      - name: Cache node_modules and pnpm store
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Lint Changed Packages
        run: turbo run lint --filter=...origin/main

      - name: Build Changed Packages
        run: turbo run build --filter=...origin/main

      - name: Test Changed Packages
        run: turbo run test --filter=...origin/main
