name: CI Pipeline

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    outputs:
      workspace_list: ${{ steps.get-workspaces.outputs.workspaces }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Get list of workspaces
        id: get-workspaces
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          
          echo "Getting all workspaces..."
          workspaces=$(pnpm recursive exec --workspace-concurrency 1 pwd)
          echo "Workspaces found: $workspaces"

          echo "Filtering workspaces..."
          filtered_workspaces=$(echo "$workspaces" | while read -r workspace; do
            if [ -f "$workspace/package.json" ]; then
              has_test=$(jq -r '.scripts.test // empty' "$workspace/package.json")
              has_build=$(jq -r '.scripts.build // empty' "$workspace/package.json")
              if [ -n "$has_test" ] || [ -n "$has_build" ]; then
                relative_path=$(realpath --relative-to="$(pwd)" "$workspace")
                echo "$relative_path"
              fi
            fi
          done | jq -R -s -c 'split("\n") | map(select(. != ""))')

          if [ -z "$filtered_workspaces" ]; then
            echo "No valid workspaces found."
            exit 0
          fi

          echo "Filtered workspaces: $filtered_workspaces"
          echo "workspaces=$filtered_workspaces" >> $GITHUB_OUTPUT
        shell: /usr/bin/bash -e {0}

      - name: Setup Node.js with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 22.6.0
          cache: "pnpm"
          cache-dependency-path: |
            pnpm-lock.yaml
            apps/**/pnpm-lock.yaml
            packages/**/pnpm-lock.yaml

      - name: Get pnpm store path
        id: pnpm-cache-path
        run: echo "pnpm_cache_path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache node_modules and pnpm store
        uses: actions/cache@v4
        id: cache-npm
        with:
          path: |
            node_modules
            ${{ steps.pnpm-cache-path.outputs.pnpm_cache_path }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Run linting check
        run: pnpm lint

  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ${{ fromJSON(needs.setup.outputs.workspace_list) }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Run turbo-ignore for typecheck
        run: npx turbo-ignore ${{ matrix.workspace }} --task=typecheck

      - name: Run typecheck
        run: pnpm typecheck
        if: ${{ success() }}

  test:
    needs: [typecheck, setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ${{ fromJSON(needs.setup.outputs.workspace_list) }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Run turbo-ignore for tests
        run: npx turbo-ignore ${{ matrix.workspace }} --task=test

      - name: Run tests
        run: pnpm test:ci
        if: ${{ success() }}

  build:
    needs: [test, setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ${{ fromJSON(needs.setup.outputs.workspace_list) }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Run turbo-ignore for build
        run: npx turbo-ignore ${{ matrix.workspace }} --task=build

      - name: Run build
        run: pnpm build
        if: ${{ success() }}
