name: Deploy to Amazon ECS

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    outputs:
      # Defining job outputs for conditional deployment:
      changed-api: ${{ steps.changed-api.outputs.result }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install turbo-ignore
        run: npm install -g turbo-ignore

      - name: Get previous commit
        id: prev-commit
        run: |
          git fetch --quiet
          echo "PREV_COMMIT=$(git rev-parse HEAD^)" >> $GITHUB_ENV

      - name: Determine if API workspace has changed
        id: changeset
        run: |
          content=$(turbo-ignore api --fallback=$PREV_COMMIT --dry-run=json)
          # Transform multi-line JSON to single-line for GitHub Actions output
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=result::$content"

      - name: Check if API has changed
        id: changed-api
        # Check if the 'api' workspace is present in the output from turbo-ignore
        if: ${{ contains(fromJSON(steps.changeset.outputs.result).packages, 'api') }}
        run: |
          echo "API workspace has changes."
          echo "::set-output name=result::true"

      - name: Login to Amazon ECR
        id: login-ecr
        if: ${{ steps.changed-api.outputs.result == 'true' }}
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag, and push API image to Amazon ECR
        id: build-image
        if: ${{ steps.changed-api.outputs.result == 'true' }}
        env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            IMAGE_TAG: ${{ github.sha }}
            ECR_REPOSITORY: squared-api
        run: |
            # Build only the api service in the docker-compose file
            docker build -f apps/api/Dockerfile -t api:latest .
            
            # Tag the built image with the ECR repository URI and push it to ECR
            docker tag api:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            
            # Output the image URI for further steps if needed
            echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        if: ${{ steps.changed-api.outputs.result == 'true' }}
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ secrets.ECS_TASK_DEFINITION }}
          container-name: ${{ secrets.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        if: ${{ steps.changed-api.outputs.result == 'true' }}
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true
