name: "Send meeting notifications"

on:
  schedule:
    - cron: "45 18 * * 0" # Runs every Sunday at 4:45 AM GMT+10
    - cron: "45 18 * * 4" # Runs every Thursday at 4:45 AM GMT+10
    - cron: "45 18 1-7,15-21 * 2" # Runs every second Tuesday at 4:45 AM GMT+10
  workflow_dispatch: # Allows manual trigger

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Send meeting notification to Discord
        env:
          DISCORD_MEETINGS_URL: ${{ secrets.DISCORD_MEETINGS_URL }}
        run: |
          MESSAGE="@everyone There is a meeting scheduled today!"

          # Send the notification to Discord
          curl -H "Content-Type: application/json" -X POST \
            -d "{\"content\": \"$MESSAGE\"}" \
            "${DISCORD_MEETINGS_URL}"
