name: "Send meeting notifications"

on:
  schedule:
    - cron: "45 17 * * 0"
    - cron: "45 17 * * 4"
  workflow_dispatch:

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Send meeting notification to Discord
        env:
          DISCORD_MEETINGS_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          MESSAGE="@everyone There is a meeting scheduled today!"

          # Send the notification to Discord
          curl -H "Content-Type: application/json" -X POST \
            -d "{\"content\": \"$MESSAGE\"}" \
            "${DISCORD_MEETINGS_URL}"
