name: Check Stale Branches

on:
  schedule:
    - cron: "0 19 * * 1" # Monday 5am GMT+10 (19:00 UTC Sunday)
  workflow_dispatch:

jobs:
  check-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stale Branches
        uses: crs-k/stale-branches@v5.0.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          days-before-stale: 30
          days-before-delete: 60
          tag-committer: true
          stale-branch-label: 'stale'
          compare-branches: 'info'
